privacytools/privacytools.io

- index.html
Better consistency considering all other addon links are in English.
> Fix uBlock Origin Addon Link to English

- CONTRIBUTING.md
- README.md
**Changes**
- Took the text from [this issue](https://github.com/privacytoolsIO/privacytools.io/issues/1) and put it in the readme.md. It is much more prominent now.
- I made the contributing guidelines in readme.md a little bit clearer with a header, bullet points and an additional example link.
- I made the warning about not submitting ideas here on GitHub friendlier so that people feel more welcome to join the discussion on Reddit.
- Added a contributing.md file. Now, when users submit an issue, they will see an alert like this:
The link will take them to contributing.md. (If you want, you can [disable issues](https://help.github.com/articles/disabling-issues/), by the way.)
- Corrected the capitalization in the tagline, in readme.md. You may want to do this for the repository …
> Improvements to readme

- index.html
I know I have commit access but I am submitting a pull request so you can confirm the change.
Thank you.
> corrected typo

- index.html
I noticed this one while reviewing #9.
> Corrected tiny grammar error

- pw.php
I am sure you must have fixed this on the server but not uploaded the changes to GitHub...?
> Fixed syntax error

- index.html
I added useful comments, arranged the code to be neater (block code), and removed two extra paragraph tags which were open and closing right next to one another with no content between the two tags.
> Commenting out index.html

- index.html
Reddit removed their Warrant Canary so I added a warning at the bottom of the page by the Reddit link
> Reddit Warrant Canary

- index.html
https://anonymous-proxy-servers.net/blog/index.php?/archives/438-End-of-Live-DVD.html
> Fix JonDo Live - mention end of support

- password.html
Is there any reason for _that_ to be there?
> Remove 'period'

- index.html
> Fix OpenMailBox forum link

- index.html
I2P-Bote is literally a decentralised e-mail alternative, Bitmessage is less of an alternative to email.
> Switch I2P-Bote and Bitmessage, update link

- index.html
All values (apart from AzireVPN which is not rounded to a whole number to not interfere with NordVPN's $48 / year) rounded, in dollars.
> Fix VPN provider table sorting

- index.html
Price `data-value`'s are in USD. As currencies' values change, I rounded the converted values.
> Fix email provider table sorting

- index.html
> Move other OTR clients to Worth Mentioning section

- index.html
Changed 'browser.safebrowsing.enabled' to
'browser.safebrowsing.phishing.enabled'
> Safebrowsing parameter updated for firefox

- index.html
https://cpj.org/blog/2016/05/why-telegrams-security-flaws-may-put-irans-journal.php
https://gizmodo.com/why-you-should-stop-using-telegram-right-now-1782557415
https://medium.com/@thegrugq/operational-telegram-cbbaadb9013a
> Add Telegram to messengers that should be avoided

- index.html
see https://conversations.im/ and https://en.wikipedia.org/wiki/Conversations_(software)
> Conversations supports OMEMO

- css/custom.css
- index.html
> Added social-share-link for Diaspora

- index.html
The Logo was not showing up because of bad file path.  Fixed.
> Fixed file path to zcash logo.  Image shows up now.

- index.html
> Add b32 mapping to I2P address

- index.html
Remove Encryptr from suggested Password Managers per https://github.com/privacytoolsIO/privacytools.io/issues/203
> Remove Encryptr

- index.html
Some button colors got mixed up as a result of an earlier reordering.
http://htmlpreview.github.io/?https://github.com/NinebitX/privacytools.io/blob/patch-2/index.html
> Fixed button colors

- README.md
The headings in the `readme.md` didn't show properly on GitHub. So I've fixed that. You can see the new readme.md here: [github.com/mat1th/privacytools.io/blob/fix/readme/README.md](https://github.com/mat1th/privacytools.io/blob/fix/readme/README.md)
http://htmlpreview.github.io/?https://github.com/mat1th/privacytools.io/blob/fix/readme/index.html
> fix headings in the readme.md

- index.html
https://www.reddit.com/r/privacytoolsIO/comments/6508gs/proposal_remove_doublehop_from_vpn_list/
http://htmlpreview.github.io/?https://github.com/Shifterovich/privacytools.io/blob/remove-doublehop/index.html
> Remove doublehop.me

- index.html
Edit to line 1178 - changed "primary" to "success" in order to change color of term "Accepted" to green. It shouldn't be blue. 
I don't know how to pull in a preview.
> Change StartMail "Accepted" Bitcoin color from blue to green

- index.html
I updated the Zcash text to be more accurate, and I updated the Dash text to be more descriptive.
> Update Zcash and Dash text

- index.html
Was removed by accident.
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/re-add-ublock-origin/index.html
> Re-add uBlock Origin

- index.html
As per @daira's suggestion in #241 
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/Shifterovich-zcash-desc/index.html
> Update Zcash description

- index.html
Fixed a couple typos and added Pixel to the CopperheadOS description as it's been supported ever since the Pixel line launched.
http://htmlpreview.github.io/?https://github.com/anoadragon453/privacytools.io/blob/master/index.html
> Add Pixel to CopperheadOS description, fix typo

- index.html
#247 #256 
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/Shifterovich-switch-btc-xmr/index.html
> Switch Bitcoin and Monero

- index.html
Reverts privacytoolsIO/privacytools.io#267
> Revert "Switch Bitcoin and Monero"

- donate.html
- index.html
- password.html
- webrtc.html
I changed the viewport to make the website responsive in mobile browsers, @Shifterovich agreed with me.
> Changed viewport to make the site mobile responsive

- index.html
Title, I've also added a little note saying that KeePassX doesn't have regular updates, feel free to use a shorter term to say that, I couldn't remember it. Brought up by #259.
Sidenote: The box is too small for all the text, should we just remove the update comment?
http://htmlpreview.github.io/?https://github.com/hugoncosta/privacytools.io/blob/patch-3/index.html
> Add KeePassXC (KeePassX's community fork)

- index.html
This fixes issue: https://github.com/privacytoolsIO/privacytools.io/issues/271
http://htmlpreview.github.io/?https://github.com/C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N/privacytools.io/blob/patch-1/index.html
> Put the Tor Browser as the #1 choice in the Browser Recommendations (Issue: 271)

- index.html
Reverts privacytoolsIO/privacytools.io#277
> Revert "Adding a Content Security Policy and Referrer Policy to index.html"

- donate.html
- password.html
- webrtc.html
The CSP changes
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/CSP-changes/index.html
> CSP - password

- index.html
I thought it would be fair to shine some light on the concept from the other side.
This reddit thread has a comment with quotes from a 2015 VPN interview by torrentfreak.
https://www.reddit.com/r/privacytoolsIO/comments/45pm24/warrant_canary/
Perhaps if there is animo for it we could make a small section under warrant cannaries with more criticism?
Link to interviews (relevant information is on page 1 and 2): https://torrentfreak.com/anonymous-vpn-service-provider-review-2015-150228
> Some criticism of warrant cannaries

- index.html
I thought DDG would fit in the same list as other privacy focused search engines. Their privacy policy is simple enough for anyone to understand, but they are clear in the workings of the search engines.
https://duckduckgo.com/privacy
> Add DuckDuckGo to worthwhile mentions

- index.html
https://www.reddit.com/r/privacy/comments/6qmzkx/best_desktop_app_for_instant_messaging_with/dkyk2an/
https://security.stackexchange.com/a/49802
Link two posts from Reddit and Stackoverflow. The posts are linking to various sources, so it's just easier to add the posts instead of linking all of the sources, the posts are also shorter than the original sources, making it easier to read for average person.
I think it's pretty important to describe why Telegram isn't secure, cause their marketing promoting it as such might be misleading for many people reading the website.
http://htmlpreview.github.io/?https://github.com/nalapl3/privacytools.io/blob/patch-1/index.html
> Telegram insecurity

- index.html
https://www.reddit.com/r/privacytoolsIO/comments/6q0umj/key_disclosure_law_update_for_norway/
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/Shifterovich-norway-kdl/index.html
> Add Norway to Key disclosure law section

- index.html
Hey!
I put [Muonium](http://github.com/muonium) as another alternative. Which is an actual encrypted cloud, opensource and so on 🐳 
http://htmlpreview.github.io/?https://github.com/Super-Baleine/privacytools.io/blob/master/index.html
> put Muonium on self hosting and cloud storage services sections

- index.html
Mastodon is a GNU Social-compatible microblogging server
http://htmlpreview.github.io/?https://github.com/ilpianista/privacytools.io/blob/master/index.html
> Reference Mastodon

- index.html
Resolves #342 , changed from No to Yes.
http://htmlpreview.github.io/?https://github.com/hugoncosta/privacytools.io/blob/patch-2/index.html
> Add Free Trial on Azire

- index.html
Update pricing of IVPN according to: https://www.ivpn.net/pricing (semi-permanent sales is considered, as it was already the case for other VPNs in this list)
http://htmlpreview.github.io/?https://github.com/Heliosmaster/privacytools.io/blob/patch-1/index.html
> Update pricing of IVPN

- index.html
Fix inconsistent No label for disroot.org
> Fix inconsistent No label

- README.md
fix typo in software criteria section of readme
http://htmlpreview.github.io/?https://github.com/emanresusername/privacytools.io/blob/patch-1/index.html
> fix typo in software criteria section of readme

- index.html
Add "Web" to Laverna supported platforms.
Proof-link: https://laverna.cc/app/
http://htmlpreview.github.io/?https://github.com/Akyshnik/privacytools.io/blob/patch-1/index.html
> Add "Web" platform for Laverna

- index.html
I think it is important that users are aware of a limitation of Privacy Badger and do not imagine that uBlock Origin is not needed when using Privacy Badger.
See: https://github.com/privacytoolsIO/privacytools.io/issues/335
http://htmlpreview.github.io/?https://github.com/woctezuma/privacytools.io/blob/privacy-badger/index.html
> Privacy Badger & Google Analytics

- index.html
http://htmlpreview.github.io/?https://github.com/[GITHUB_USERNAME]/privacytools.io/blob/[BRANCH]/index.html
> Update Least Authority S4 Pricing

- index.html
#377. In addition to replacing the link, I have also changed the title accordingly.
http://htmlpreview.github.io/?https://github.com/hugoncosta/privacytools.io/blob/patch-5/index.html
> Replace deadlink on SpiderOak VPN Info

- index.html
Issue #381 
IVPN price changed to $100
http://htmlpreview.github.io/?https://github.com/Eduardo06sp/privacytools.io/blob/patch-1/index.html
> For Issue #381 Update VPN Price

- index.html
http://htmlpreview.github.io/?https://github.com/Tornado1878/privacytools.io/blob/master/index.html
> Small Typo Fix

- index.html
http://htmlpreview.github.io/?https://github.com/sachk/privacytools.io/blob/master/index.html
> Fix typo with Bitcoin Cash.

- index.html
http://htmlpreview.github.io/?https://github.com/quiddity-wp/privacytools.io/blob/master/index.html
> Update RetroShare URL - moved to github 2 years ago

- index.html
I have localized privacytools.io (besides adding new things that I will add with a later push request) into Italian and added a link to the website
https://htmlpreview.github.io/?https://github.com/Strappazzon/privacytools.io/blob/patch-1/index.html
> Add a link to the Italian localization

- index.html
Added LUKS to File Encryption Software (Worth Mentioning) as [per this thread on reddit](https://redd.it/7z5lwh), and issue #152.
https://htmlpreview.github.io/?https://github.com/michaelplews/privacytools.io/blob/adding-LUKS/index.html#encrypt
> Added LUKS to File Encryption Software worth mentioning section

- index.html
Closes #409 by updating the Torrentfreak article to latest. Kept sponsored link warning since it probably still applies.
http://htmlpreview.github.io/?https://github.com/spadesr/privacytools.io/blob/409-update-torrentfreak-article/index.html
> Updates torrentfreak vpn article

- index.html
Small change that closes issue #410 by setting disroot's own domain value to 'Yes'. Verified that support for own domains was indeed added to disroot.
http://htmlpreview.github.io/?https://github.com/spadesr/privacytools.io/blob/410-disroot-own-domain-support/index.html
> Changes disroot own domain support to yes

- index.html
- updated EteSync to include Web as an OS
- updated EteSync description to mention it supports CalDAV/CardDAV
- modified various wording in the section for clarity
see #417 post-merge comments
https://htmlpreview.github.io/?https://github.com/neverducky/privacytools.io/blob/calendar_contacts-change-etesync-info/index.html#calendar_contacts
> update calendar/contacts sync info and wording

- index.html
https://www.hrw.org/news/2016/07/12/russia-big-brother-law-harms-security-rights
http://htmlpreview.github.io/?https://github.com/c0rdis/privacytools.io/blob/master/index.html
> Added Russia to "Key disclosure law" section

- img/flags/4x3/ru.svg
Added Russian flag to the same location as other flags, as it wasn't originally in the folder for commit #423 
http://htmlpreview.github.io/?https://github.com/c0rdis/privacytools.io/blob/f92f3169246bc3fd0822dd7e5f9624297015b3b0/img/flags/4x3/ru.svg
> Added Russian flag to /img/flags/4x3/ru.svg

- README.md
- index.html
Added Russian translation
http://htmlpreview.github.io/?https://github.com/c0rdis/privacytools.io/blob/master/index.html
> russian translation

- index.html
fixes #416 
http://htmlpreview.github.io/?https://github.com/[GITHUB_USERNAME]/privacytools.io/blob/[BRANCH]/index.html
> Fix Issue #416: Update information about patched incompatiblity with add-on

- index.html
Fixes a small typo and adds a missing "a" in the description for Write.as.
http://htmlpreview.github.io/?https://github.com/thebaer/privacytools.io/blob/patch-writeas-typo/index.html
> Fix small typo in Write.as description

- index.html
This addresses issue #447, removing information that Conversations supports OTR and adding information about Conversations Legacy.
http://htmlpreview.github.io/?https://github.com/infosec-handbook/privacytools.io/blob/patch-1/index.html
> Updated Conversations and Conversations Legacy

- index.html
Added Matrix and Riot.im to the worth mentioning list of the instant messaging section.
#433 #411 #220
First commit about ghostbin isn't present in this branch (is #435)
http://htmlpreview.github.io/?https://github.com/sevengali/privacytools.io/blob/sevengali-matrix/index.html
> Matrix protocol / Riot.im client

- index.html
I added a warning about Signal needing a mobile number to register. #432 
First commit about ghostbin isn't present in this branch (is #435)
http://htmlpreview.github.io/?https://github.com/sevengali/privacytools.io/blob/sevengali-signal/index.html
> Added warning about Signal

- index.html
Under German law, you are allowed to refuse giving your keys to authorities.
> Add Germany to Key Disclosure Subsection

- index.html
Add onion url to njalla
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/njalla-tor/index.html
> Onion url for njalla

- index.html
Fix URL
http://htmlpreview.github.io/?https://github.com/macau23/privacytools.io/blob/fix-masterpassword-url/index.html
> Fix url for masterpassword

- index.html
http://htmlpreview.github.io/?https://github.com/[GITHUB_USERNAME]/privacytools.io/blob/[BRANCH]/index.html
> Remove CopperheadOS

- index.html
This should fix #438 
http://htmlpreview.github.io/?https://github.com/Raviu8/privacytools.io/blob/patch-2/index.html
> Remove syncany as development is ceased. Fix #438

- .github/PULL_REQUEST_TEMPLATE.md
Change http to https to the PR template
> Change http to https to the PR template

- index.html
Add missing alt text and remove stray end tags for all images .
https://htmlpreview.github.io/?https://github.com/Vincevrp/privacytools.io/blob/master/index.html
> Add missing alt text and remove stray end tags

- index.html
`<ul>` elements should not be allowed as a child of an `<ol>` element.
https://htmlpreview.github.io/?https://github.com/Vincevrp/privacytools.io/blob/list-fix/index.html
> Fix invalid lists

- css/custom.css
- index.html
Replaced inline CSS and obsolete align attribute with a class for all images in `.panel-body`
https://htmlpreview.github.io/?https://github.com/Vincevrp/privacytools.io/blob/master/index.html
> Create panel-item class to replace inline CSS

- index.html
Remove unnecessary span tags. This also improves responsiveness.
https://htmlpreview.github.io/?https://github.com/Vincevrp/privacytools.io/blob/span-fix/index.html
> Remove unnecessary span tags

- index.html
Removed buttons tags and placed their classes on the anchor links.
https://htmlpreview.github.io/?https://github.com/Vincevrp/privacytools.io/blob/button-fix/index.html
> Remove unnecessary button tags

- index.html
Removed table rows without cells.
https://htmlpreview.github.io/?https://github.com/Vincevrp/privacytools.io/blob/table-fix/index.html
> Remove table rows without cells

- index.html
https://htmlpreview.github.io/?https://github.com/dpeukert/privacytools.io/blob/patch-1/index.html
> Add Search Engines link to the menu and fix some spacing

- css/custom.css
- index.html
Reworked donated button to improve looks and fix W3 error. Small changes to nav to improve responsiveness as well. 
https://htmlpreview.github.io/?https://github.com/Vincevrp/privacytools.io/blob/donate-button/index.html
> Rework donate button

- css/custom.css
- index.html
Replace obsolete anchor tags with .anchor class.
No preview because of Jekyll.
> Replace obsolete anchor tags with .anchor class

- _layouts/default.html
https://htmlpreview.github.io/?https://github.com/[GITHUB_USERNAME]/privacytools.io/blob/[BRANCH]/index.html
> append links to css&js files with ?v=4 to bypass cache

- index.html
We use no article with plural nouns.
> Remove an article from the sentence

- index.html
#511 
> The project has only 2 contributors and is added by one of the authors of the software package.
> I personally think privacytoolsIO should recommend proven solutions, not alpha/beta software.
> I found the github link on bottom of muonium.io but repo is active on gitlab. You have to register to use it. Upon registration, you are redirected to https://mui.cloud/
> 
> Above page loads:
> 
> font-awesome/css/fontawesome.min.css
> fonts/Roboto.css
> 
> ...and three js scripts. This gives a lot of opportunities to google for fingerprint the users.
> Like all cloud solutions that allegedly care about privacy, they really fail at it.
> 
> However, Font Awesome does use services from other companies to provide fontawesome.com, content delivery networks, and to distribute and develop icons …
> Remove Muonium

- index.html
https://spideroak.com/articles/guest-post-can-you-trust-a-vpn-to-protect-your-privacy/ article does not exist anymore.
> Delete non-existent article

- donate.html
- webrtc.html
Fix assets path for donate and webrtc pages
> Fix assets path for donate and webrtc pages

- index.html
This pull request relates to #549.
Closes #549
> Add missing commas to conditional sentences

- README.md
> Fix logo URL in README

- index.html
This pull request closes #566.
> Remove Tox recommendation

- Gemfile
- _config.yml
Clean up Gemfile and _config.yml. I added the `github-pages` gem to the Gemfile to avoid inconsistencies, as explained [here](https://jekyllrb.com/docs/github-pages/#the-github-pages-gem)
> Config cleanup

- index.html
> Fix add-on spelling

- 404.html
Resolves issue #600 
Fix 404 page and add automatic redirect.
> Fix 404 page and add redirect

- assets/css/style.scss
- index.html
Fix lists and order in key disclosure law section.
Resolves: #604
> Fix list and order in KDL

- index.html
OSALT and AlternativeTo are great directories to find alternatives to proprietary software. Which, in its self might not be a privacy feature, but is a security feature. 
https://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/adc6405d115606af2b5ca2a9f0072ab17753754a/index.html
> Add OSALT and AlternativeTo to the Tools List

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
* Move contributing guidelines to `.github/CONTRIBUTING.md`
* Fix build instructions in README
* Update PR template with new guidelines
> Move contributing guidelines and fix build instructions

- index.html
After 2.5+ years without change, I suggest removing the old KeePassX completely and slightly expanding the explanation for KeePassXC. Thanks!
> remove the old KeePassX completely

- index.html
Sailfish is non-free software and therefore does not qualify.
Source: https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md#software-criteria
Sailfish provides few security and privacy advantages.
> Remove Sailfish

- index.html
> Remove unused Password Generator entry

- index.html
Remove the text "Matrix [...] successor of XMPP"
> Remove the text "Matrix [...] successor of XMPP"

- index.html
Move link from http to https when it's possible
> Move http → https when it exists

- index.html
No more canary for vpnsecure.me
> No more canary for vpnsecure.me

- index.html
Change the link to point to the anonymous mode (old one was deprecated and redirected to the main website)
> Fix dudle's link

- README.md
This PR adds the travis-ci build badge to `README.md`
> Add travis-ci badge to README

- _layouts/default.html
- index.html
The VPN table was quite outdated - reviewed and fixed number of servers, price and in case of Perfect Privacy - country (from Panama to Switzerland, see https://www.perfect-privacy.com/imprint). Also smaller fixes for better sorting of the table.
> Actualized VPN table

- _layouts/default.html
Added FA icons, removed unnecessary sections
(@c0rdis #704)
> Reworked layout

- _layouts/default.html
Adds feature where the navbar auto collapses on mobile after clicking on one of the links.
> Navbar autocollapse on mobile

- _includes/sections/notebooks.html
removed old text about laverna
Resolves: #737
> Remove old code in notebooks section

- _includes/sections/password-managers.html
Reverts privacytoolsIO/privacytools.io#720
https://github.com/privacytoolsIO/privacytools.io/issues/719#issuecomment-454454146
@kspearrin ping
> Restore BitWarden

- _includes/sections/voice-video-messenger.html
Ring has recently be renamed, additional details located in the issue
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/750
> change ring to jami & update url

- _includes/sections/browser-tweaks.html
Title. Request #577. For now, this seems about right, should a reform happen on the Firefox setting, I believe we should give a bigger emphasis to "all-in-one" tutorials like this one.
> Add atomGit's guide to related info

- _includes/sections/email-clients.html
- _includes/sections/email-providers.html
Resolves: #150 
I also moved the email privacy tools to the email clients section.
> Add Torbirdy notice

- _includes/sections/key-disclosure-law.html
- _includes/sections/password-managers.html
> Replacing Youtube (GoogleTube) with Peertube.

- _includes/sections/browser-tweaks.html
> Adds extensions.pocket.enabled false

- _includes/sections/notebooks.html
> adding notable to worth mentioning section

- _includes/nav.html
> Add PrivateBin

- _includes/sections/password-managers.html
Added Psono as password manager
> Added Psono

- assets/css/style.scss
Better text wrapping on iOS Safari.
> Fix mobile wrapping

- _includes/sections/key-disclosure-law.html
> shorter description

- _includes/sections/resources.html
- pages/old.html
> Rename /old/ to /classic/

- _includes/nav.html
- _includes/sections/participate.html
- contact.md
- pages/services.html
`#general:privacytools.io` and https://riot.privacytools.io/
> Add Matrix Channel/Server

- donate.html
> recommended -> listed

- _includes/footer.html
- _includes/nav.html
> Contact and donate link

- README.md
I added the link to privacytools-fr and its source code.
> Add French to Community Translations

- _includes/sections/key-disclosure-law.html
https://iclg.com/practice-areas/cybersecurity-laws-and-regulations/italy (Section 8.2)
https://www.brocardi.it/codice-di-procedura-penale/libro-terzo/titolo-ii/capo-i/art198.html#dispositivo
> Add Italy to Key Disclosure Law

- _includes/sections/calendar-contacts-sync.html
- _includes/sections/participate.html
- _includes/sections/search-engines.html
I attempted to fix the broken legacy anchors. 
Resolves: #842
> Fixed legacy anchors

- _includes/nav.html
really small change but it is absolutely required and necessary the world will end if this isn't included trust me
> "Avoid US & UK services" in the header now links to the proper section

- donate.html
> removed paypal logo

- _includes/sections/browser-tweaks.html
> browser-tweaks: remove browser.send_pings

- _includes/footer.html
http://privacy2zbidut4m4jyj3ksdqidzkw3uoip2vhvhbvwxbqux5xy5obyd.onion/
> Add Tor Address to Footer

- _includes/nav.html
I haven't validated anything on their site, so I'm just taking their word that they are indeed finished with their translation. If someone wants to validate everything before approval that'd be great :)
Resolves: #830
> Add Portuguese Language

- _includes/sections/instant-messenger.html
Added ThinkPrivacy.io messenger comparison chart as requested on forum.
> added messenger compare link

- README.md
> update Readme. License and added Discourse link

- _includes/sections/productivity-tools.html
Lot of people are using VSCode for editing, but ususally don´t know that it tracks them or that there is an alternative.
> Add VSCodium

- README.md
- _includes/nav.html
for issue #866 
_discard if no make sense_
> Sorted the items alphabetically in nav bar

- _includes/sections/windows10.html
> windows10: remove broken links

- _includes/sections/browser-tweaks.html
> browser-tweaks: note privacy.trackingprotection.fingerprinting|cryptomining is FF67+

- _includes/sections/search-engines.html
> search-engines: add Mojeek to worth mentioning

- _includes/sections/browser-addons.html
> Remove warning about Privacy Badger and Google Analytics (#1022)

- _includes/footer.html
> Center icons correctly in share buttons

- _includes/sections/instant-messenger.html
> instant-messenger: correct supported platforms of Gajim

- _includes/card.html
- _includes/sections/browser-addons.html
- _includes/sections/browser-tweaks.html
- _includes/sections/file-sharing.html
- _includes/sections/key-disclosure-law.html
- _includes/sections/search-engines.html
- _includes/sections/self-contained-networks.html
- _includes/sections/selfhosted-cloud.html
- _includes/sections/social-networks.html
- contact.md
- donate.html
- source_code.md
My neovim config shows it using red background, it was annoying.
> Remove trailing whitespace characters at the end of lines

- _includes/sections/email-providers.html
- _includes/sections/vpn.html
This PR increases the consistency between the Email and VPN provider tables. If these changes should be separated into additional PRs, please let me know 🤓
1. Uses the same vocabulary, e.g. "Email/VPN Provider", for the first column.
2. Highlights the first column to bring visibility to users that the columns are sortable.
3. Uses the same vocabulary, e.g. "Yearly Price", for the yearly price column (rather than "Price / Year").
4. Uses the same vocabulary, e.g. "Jurisdiction", for jurisdiction column (rather than "Server").
5. Added "Since" column to VPN table with info gathered from here:
- [AirVPN, since 2010](https://airvpn.org/aboutus/)
- [AzireVPN, since 2012](https://www.azirevpn.com/about/)
- [blackVPN, since 2009](https://www.blackvpn.com/about/)
- [Cryptostorm, since …
> Highlight first columns in Email and VPN tables and consolidate column names

- .github/ISSUE_TEMPLATE/3_Discussion.md
Related to a comment @Mikaela made in # 977.
> Update discussion issue template to direct new discussions to the forum

- _includes/sections/operating-systems.html
- source_code.md
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1088
> Remove Subgraph OS

- _includes/sections/email-providers.html
> Replace "Yes" with "Accepted", which was used in other rows

- _includes/sections/notebooks.html
E2EE means "End-to-end encryption", so encryption was there twice
> Change "E2EE encryption" to "E2E encryption"

- README.md
Hey, I also want  to be there ;p
> Add Polish translation to README.md

- _includes/nav.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1107
> Add link to Calendar/Contacts Sync Tools page to navbar

- _includes/footer.html
> Align "Tor v3: priv…" to left, to make it look beter on small screens

- _includes/cardv2.html
Fixes #905
don't worry, 2 firefox icons are not in the commit
> Fix icons looking out of place on smaller screens

- .github/PULL_REQUEST_TEMPLATE.md
**Description**: Many users don't appear to be reading or know how to find the contributing guidelines.
My PR just adds some check boxes that may be helpful for new users.
It also adds a link to CONTRIBUTING.md :)
> Add Checklist to PRs

- source_code.md
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1113
> Add Social News Aggregators to source_code.md

- .github/ISSUE_TEMPLATE/7_DNS_provider.md
Resolves: #1109 
https://github.com/Mikaela/privacytools.io/issues/new/choose
> Document the criteria for DNS servers

- _includes/sections/browser-tweaks.html
Resolves: #785
Preview: https://deploy-preview-1127--privacytools-io.netlify.com/browsers/#about_config
> browser-tweaks: document TRR/DoH

- _includes/nav.html
> Remove duplicate "Social Networks" in navbar

- _includes/sections/operating-systems.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1142
> Update Qubes OS Tor link

- _includes/sections/vpn.html
In the meantime as we get #1139 sorted out, it seems like a higher priority to delist this provider specifically.
Resolves: #1131
> Remove VPN.ht

- _includes/cardv2.html
- _includes/sections/live-operating-systems.html
- _includes/sections/mobile-operating-systems.html
- _includes/sections/operating-systems.html
- _includes/sections/router-firmware.html
https://deploy-preview-1148--privacytools-io.netlify.com/operating-systems/
> Convert operating systems to cardv2.html

- .github/CONTRIBUTING.md
I just realized that the criteria is documented only in the issue template while someone suggesting a provider might opt to directly open a PR.
> CONTRIBUTING.md: fix typo & add DNS criteria

- _includes/sections/calendar-contacts-sync.html
Not sure how valuable it is to list Flock while it isn't easily consumable for users. So this removes it.
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1159
> Remove Flock

- _includes/sections/email-providers.html
Resolves https://github.com/privacytoolsIO/privacytools.io/issues/1158
> Update Disroot's mailbox size

- pages/old.html
Preview: https://deploy-preview-1165--privacytools-io.netlify.com/classic/#teamchat
> Add teamchat to /classic

- _includes/sections/vpn.html
This PR updates the small section under the VPN table. There are duplicate links to https://thatoneprivacysite.net and I think Yael Grauer's [recent research](https://thewirecutter.com/reviews/best-vpn-service) should be added since it's probably one of the best, recent in-depth looks at the VPN landscape.
Resolves: a comment I made in 1139
> Update links in "More VPN Providers"

- _includes/sections/file-encryption.html
Somehow missed that the `a href` didn't have a close tag from the original PR (https://github.com/privacytoolsIO/privacytools.io/pull/1168) :sweat_smile: 
> Fix Hat.sh link

- _includes/sections/teamchat.html
Code Repository (if applicable):
> Change Experimental to Warning in Keybase

- _includes/nav.html
- _includes/scripts.html
- assets/css/style.scss
- assets/js/main.js
Fixes #877, Fixes #872, Closes #1195.
No Javascript needed, that's why I even started it :)
> [WIP] Rewrite navbar

- _includes/scripts.html
- assets/js/main.js
I'm so sorry, please forgive me.
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1202
> Fix tooltips

- _includes/sections/dns.html
- source_code.md
Resolves: #1187
* Netlify preview for the mainly edited page: https://deploy-preview-1200--privacytools-io.netlify.com/providers/dns/#icanndns
* Code Repository (if applicable): https://git.frostnerd.com/PublicAndroidApps/smokescreen/
> DNS: add Nebulo as worth mentioning & warn about DoH metadata & sort worth mentioning/additional information into sublists

- _includes/nav.html
> Remove translation with broken TLS

- _includes/sections/privacy-resources.html
Pointed out at https://codeberg.org/crimeflare/cloudflare-tor/issues/28#issuecomment-5327
Preview: https://deploy-preview-1205--privacytools-io.netlify.com/#resources
> privacy-resources: sort information, fix cloudflare-tor link & move it to information

- _includes/footer.html
- _includes/scripts.html
- about/javascript/index.html
- assets/js/main.js
> Make JavaScript work with LibreJS

- _includes/sections/browser-tweaks.html
Ref: https://github.com/privacytoolsIO/privacytools.io/issues/1212#issuecomment-524598044
> about:config: delete geo.enabled

- _includes/sections/dns.html
Fixes https://github.com/privacytoolsIO/privacytools.io/issues/1199
It's not a question mark, because it seemed to me like we are not sure about that they support DoT or something, huh.
* https://deploy-preview-1232--privacytools-io.netlify.com/providers/dns/#icanndns
> Indicate that there is information on DoT hover

- _includes/sections/dns.html
> Fix DNS table, it did contain text under it

- _includes/head.html
- assets/css/dark.scss
This PR fixes the dark theme's input forms colors.
|Before|After|
|---|---|
|![](https://user-images.githubusercontent.com/19752093/63976744-4d37c200-cab2-11e9-9b95-814fb6b3aeaf.png)|![](https://user-images.githubusercontent.com/19752093/63976764-59238400-cab2-11e9-9370-f7c954496bd6.png)|
> Fix dark theme's input forms colors

- _includes/nav.html
why? because toggling dark mode made the navbar shift slightly which looked bad
> Fullwidth icons in navbar

- _includes/sections/browser-tweaks.html
Resolves: #1240 (see for reason)
Resolves: #1244
* https://deploy-preview-1245--privacytools-io.netlify.com/browsers/#user.js
> browser-tweaks: remove pyllyukko & add an anchor

- _includes/sections/browser-addons.html
Changes "For Experts Only" to "For Power Users Only" in the add-ons section to prevent scaring new users away.
Resolves: #1247
> Change "for Experts only" to " For Power Users only" in the addons section.

- _includes/sections/operating-systems.html
Ref: #904 where cpu.fail was mentioned
* https://deploy-preview-1231--privacytools-io.netlify.com/operating-systems/#os
> operating-systems.html: add a warning for Linux/CPU vulns

- _includes/sections/dns.html
Fixes #1267
* Netlify preview for the mainly edited page: https://deploy-preview-1266--privacytools-io.netlify.com/providers/dns/#icanndns
> Add US & DK as choices for UncensoredDNS

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/7_DNS_provider.md
- _includes/sections/dns.html
`dig` on Windows doesn't exist so I added [`Resolve-DnsName`](https://docs.microsoft.com/en-us/powershell/module/dnsclient/resolve-dnsname?view=win10-ps).
* Netlify preview for the mainly edited page: https://deploy-preview-1234--privacytools-io.netlify.com/providers/dns/
> Add Resolve-DnsName to QNAME Minimization under DNS validation section

- _includes/sections/dns.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1265
* Netlify preview for the mainly edited page: https://deploy-preview-1271--privacytools-io.netlify.com/providers/dns/#icanndns
> Remove stale source code link for Cloudflare DNS

- _includes/sections/browser-recommendation.html
> Fix Privacy Browser's warning badge and format code nicely

- contact.md
… and it's not that "New", I guess.
https://deploy-preview-1246--privacytools-io.netlify.com/contact/
> Remove mention of XMPP bridge, we don't have one

- _includes/sections/browser-tweaks.html
This is a secondary PR for the browser page. It aims to improve the about:config section and is part of the browser overhaul. It is heavy work in progress. We collaborate together with @thorin-oakenpants for this.
Resolves: #1212 
* Netlify preview for the mainly edited page: https://deploy-preview-1262--privacytools-io.netlify.com
related pull request: #1256
> [WIP] Browser overhaul. About:config section.

- _includes/sections/file-sharing.html
- source_code.md
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/407
* Code Repository (if applicable): https://salsa.debian.org/freedombox-team
> Add FreedomBox

- _includes/nav.html
- _includes/sections/productivity-tools.html
- Add navbar link to metadata removal tools [Productivity Tools](https://www.privacytools.io/software/productivity/) subsection in  (just like [Email Alternatives](https://www.privacytools.io/software/email/#messaging) and [Email Clients](https://www.privacytools.io/software/email/) point to different subsections).
- Move 'worth mentioning' under Productivity Tools subsection.
* Code Repository (if applicable): N/A
> Add navbar link to metadata removal tools

- _includes/nav.html
- contact.md
- Link to the [Contact page](https://www.privacytools.io/contact/) from the navbar
- Update the Contact page with
- a link to our Keybase team
- a link to our CoC
- updated section titles for clearer organization  
- ~~[ ] I have [listed the source code](https://github.com/privacytoolsIO/privacytools.io/blob/master/source_code.md).~~
* Netlify preview for the mainly edited page: https://deploy-preview-1311--privacytools-io.netlify.com/contact/ 
* ~~Code Repository (if applicable):~~
> Update and link to contact page from navbar

- _includes/card.html
- _includes/footer.html
- Removes the `Website:` prefix from cardv1 for consistency with cardv2
- Removes the `www.` prefix from the privacytools.io Copy & Paste link for consistency
- Removes full host name from Licenses link for consistency
- ~~[ ] I have [listed the source code](https://github.com/privacytoolsIO/privacytools.io/blob/master/source_code.md).~~
* ~~Code Repository (if applicable):~~
> Update cardv1 website link

- _includes/card.html
- _includes/panel.html
> Use bigger bottom margin in card.html and panel.html

- _includes/sections/selfhosted-cloud.html
https://deploy-preview-1329--privacytools-io.netlify.com/software/cloud/
> Convert selfhosted-cloud.html to cardv2

- pages/providers/vpn.html
change anonymity to privacy in criteria
I changed the anonymity section to privacy, as we already state that vpn providers give no anonymity, and this makes us contradict ourselves
* Netlify preview for the mainly edited page: https://deploy-preview-1344--privacytools-io.netlify.com
> Change Anonymity to Privacy in VPN criteria

- _includes/sections/dns.html
Resolves: #1207
* Netlify preview for the mainly edited page: https://deploy-preview-1339--privacytools-io.netlify.com/providers/dns/#icanndns
> DNS: add Snopyta

- .github/CODEOWNERS
Just so nobody will be able to merge trash bloated svgs with Inkscape extensions :P
> Make @dawidpotocki CODEOWNER /font/

- _includes/sections/self-contained-networks.html
* Netlify preview for the mainly edited page: https://deploy-preview-1277--privacytools-io.netlify.com/software/networks/#darknets
* Code Repository (if applicable): https://github.com/ipfs-shipyard/ipfs-companion
> self-contained-networks: add IPFS Companion, badgeize warning

- _includes/sections/operating-systems.html
> Put Worth Mentioning before CPU vulnerability mitigations

- _includes/sections/operating-systems.html
Co-authored-by: Dawid Potocki <dpot@disroot.org>
> operating-systems: add Linux in front of kernel

- _includes/sections/self-contained-networks.html
As yggdrasil has a danger badge for a "privacy warning", change the "important privacy warning" in IPFS from a warning to a danger badge
> Changed warning to danger

- _includes/nav.html
This reverts commit 257cb1af194126957f548292573faa04559c3134. Fixes #1390.
> Revert "Navbar: sort Browser & OS sections (#1304)"

- _includes/footer.html
- _includes/head.html
- _includes/nav.html
- _includes/scripts.html
- assets/css/style.scss
- assets/js/main.js
- pages/donate.html
you guys like to break everything
> Remove inline JavaScript

- _includes/sections/operating-systems.html
Resolves: #1404
* Netlify preview for the mainly edited page: https://deploy-preview-1411--privacytools-io.netlify.com/operating-systems/#cpuvulns
> operating-systems: add link to cyberciti on microcode updates

- _includes/sections/calendar-contacts-sync.html
- _includes/sections/vpn.html
Updated the figures for number of servers and countries for VPNs, and updated the price of EteSync.
https://deploy-preview-1438--privacytools-io.netlify.com/providers/vpn/
https://deploy-preview-1438--privacytools-io.netlify.com/software/calendar-contacts/
> Update EteSync pricing and VPN server data

- _includes/sections/dns.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1424 
* Netlify preview for the mainly edited page: https://deploy-preview-1455--privacytools-io.netlify.com/providers/dns/#icanndns
> Replace BlahDNS's Switzerland server with its new Finland server

- _includes/sections/resources.html
- _includes/sections/selfhosted-cloud.html
* Update resources.html
* Update selfhosted-cloud.html to make it more consistent with other the 
wording of the other Nextcloud entry in cloud storage
> Fix some minor typos

- _includes/sections/self-contained-networks.html
Resolves: #1460 
* Netlify preview for the mainly edited page: https://deploy-preview-1462--privacytools-io.netlify.com/software/networks/
> self-contained-networks: add privacy warning to ZeroNet

- _includes/sections/browser-tweaks.html
Link to https://blog.privacytools.io/firefox-privacy-an-introduction-to-safe/ in additional resources for browser modifications.
* Netlify preview for the mainly edited page: https://deploy-preview-1476--privacytools-io.netlify.com/browsers/#about_config
> Add link to Firefox privacy blog post

- _includes/sections/cloud-storage.html
See https://github.com/privacytoolsIO/privacytools.io/pull/1484
https://deploy-preview-1494--privacytools-io.netlify.com/providers/cloud-storage/
> Warn Cryptomator mobile apps not open source in cloud storage

- _includes/sections/notebooks.html
- _includes/sections/teamchat.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1511
* Netlify preview for the mainly edited page: https://deploy-preview-1512--privacytools-io.netlify.com/software/notebooks/#notebook
> Add link to audit for Standard Notes

- _includes/sections/email-providers.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1268
* Netlify preview for the mainly edited page: https://deploy-preview-1513--privacytools-io.netlify.com/providers/email/#email
> mailbox.org no long accepts Bitcoin

- _includes/footer.html
- pages/privacy.md
Keys the privacy statement. Please see my comment below.
> i18n: Key the privacy statement

- _includes/sections/email-providers.html
I changed mailbox.org's bitcoin `data-value` according to the changes introduced by #1513 
* Netlify preview for the mainly edited page: https://deploy-preview-1523--privacytools-io.netlify.com/providers/email/
> Change mailbox.org's bitcoin data-value

- _includes/sections/vpn.html
- pages/providers/vpn.html
Resolves PR https://github.com/privacytoolsIO/privacytools.io/issues/1435
> IPv6 badge for Mullvad 

- pages/providers/vpn.html
Addition of a responsible marketing section. These things often come up in discussion on the forums, and in other PRs.
> Addition of reponsible marketing section

- _includes/footer.html
- _includes/nav.html
It still worked without the quotes, but it's better for consistency
> i18n: add href quotes

- _includes/sections/calendar-contacts-sync.html
- _includes/sections/productivity-tools.html
Resolves: #1416 
* Netlify preview for the mainly edited page: https://deploy-preview-1530--privacytools-io.netlify.com/software/calendar-contacts/#calendar_contacts
* Code repository of the project (if applicable): https://github.com/39aldo39/DecSync
> Software Suggestion | DecSync

- pages/providers/email.html
- pages/software/email.html
> Fix typos in email.html

- .github/CODEOWNERS
- README.md
- _includes/footer.html
- pages/notices.md
https://deploy-preview-1558--privacytools-io.netlify.com/notices/
> Legal Cleanup

- _includes/sections/vpn.html
https://deploy-preview-1571--privacytools-io.netlify.com/providers/vpn/
> Mention standard/pro account for IVPN

- _includes/sections/vpn.html
- pages/providers/vpn.html
https://deploy-preview-1570--privacytools-io.netlify.com/providers/vpn/
> Remote port forwarding badge for VPN providers

- _includes/sections/instant-messenger.html
https://deploy-preview-1569--privacytools-io.netlify.com/software/real-time-communication/#peer-to-peer
> Recommend "Tox" over "qTox"

- _includes/sections/instant-messenger.html
https://deploy-preview-1574--privacytools-io.netlify.com/software/real-time-communication/#federated
Resolves https://github.com/privacytoolsIO/privacytools.io/issues/1561
> Mention XSF instead of "foundation" and reword.

- .github/ISSUE_TEMPLATE/4_Feature.md
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1604
> Remove `:` from 4th issue template

- _includes/sections/teamchat.html
Resolves: #1599
Thanks to @rm-rf-home for noticing
* Netlify preview for the mainly edited page: https://deploy-preview-1609--privacytools-io.netlify.com/software/real-time-communication/#teamchat
> teamchat: fix Keybase typo though -> through

- _includes/sections/vpn.html
According to their newsletter 80 servers have been added since november.
Update ProtonVPN number of servers
> Update number of ProtonVPN servers

- _includes/sections/instant-messenger.html
See https://github.com/privacytoolsIO/privacytools.io/issues/1611
* Netlify preview for the mainly edited page: https://deploy-preview-1612--privacytools-io.netlify.com/software/real-time-communication/
> Relocate warning text in Encrypted IM

- _includes/sections/dns.html
> Remove DNSCrypt from Cloudflares listed protocols

- .github/ISSUE_TEMPLATE/1_Software_Suggestion.md
- .github/ISSUE_TEMPLATE/2_Software_Removal.md
- .github/ISSUE_TEMPLATE/7_DNS_provider.md
- .github/PULL_REQUEST_TEMPLATE.md
Resolves: a lot of issues I have with the issue tracker recently...
* Netlify preview for the mainly edited page: N/A
> Request issue/PR opener to disclose their connection to the software, why they are suggesting it and keep us up-to-date

- _includes/sections/file-sharing.html
The link was not working for me. So I changed it based on what is on the bottom of OnionShare's website.
Resolves: #none. This is currently not an open issue (that I know of).
- [ x] I have read and understand [the contributing guidelines](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md).
- [x ] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software
> Update Tor link for OnionShare

- _includes/sections/quotes.html
* Netlify preview for the mainly edited page: https://deploy-preview-1654--privacytools-io.netlify.com/
> Update Edward Snowden quotes from Permanent Record

- _includes/sections/vpn.html
https://deploy-preview-1667--privacytools-io.netlify.com/providers/vpn/
Resolves: #1664
> Move IVPN into recommended section

- _includes/sections/vpn.html
https://deploy-preview-1675--privacytools-io.netlify.com/providers/vpn/
Just a small consistency error that I made with the #1667
> Add visit link for IVPN

- pages/software/real-time-communication.html
I guess AG Barr is back from Christmas holidays!
Latest news on the war on end to end encryption.
> EARN IT ACT, a workaround for banning E2EE

- pages/about.html
This adds the fact that i have become editor in chief, and adds my name.
> Add information to my about entry.

- _includes/sections/vpn.html
https://deploy-preview-1688--privacytools-io.netlify.com/providers/vpn/
This style is used in #1672
> Normalize links for VPN section

- pages/sponsors.html
Closes #1508 @davegson
https://deploy-preview-1690--privacytools-io.netlify.com/sponsors/
> Clarify sponsorship policy

- _includes/sections/quotes.html
Resolves: #1629  
- ~~[ ] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software~~
* Netlify preview for the mainly edited page: https://deploy-preview-1709--privacytools-io.netlify.com/#sponsors
> Add Chelsea Manning quote to home page

- _includes/sections/notebooks.html
Resolves: #1716
* Netlify preview for the mainly edited page: https://deploy-preview-1724--privacytools-io.netlify.com/software/notebooks/
> Remove Notable from Digital Notebooks

- _includes/sections/search-engines.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1711
* Netlify preview for the mainly edited page: https://deploy-preview-1712--privacytools-io.netlify.com/providers/search-engines/
> Update public Searx instances link

- _includes/sections/email-providers.html
Correction made from comment: [fj6pkjl](https://reddit.com/r/privacytoolsIO/comments/fbt8nd/our_new_email_page_is_now_live/fj6pkjl/)
https://deploy-preview-1748--privacytools-io.netlify.com/providers/email/#protonmail
> Catchall only with Professional/Visionary accounts

- _includes/sections/dns.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1745
* Netlify preview for the mainly edited page:  https://deploy-preview-1746--privacytools-io.netlify.com/providers/dns/#dns
> Remove Dnswarden [no longer maintained] 

- _includes/sections/search-engines.html
Approved issue by @blacklight447-ptio 
https://github.com/privacytoolsIO/privacytools.io/issues/1739#issuecomment-593086290
Resolves: #1739  
> Removal of Jive Search due to #1739

- _includes/sections/email-providers.html
https://deploy-preview-1754--privacytools-io.netlify.com/providers/email/
> Remove emphasis, correct disroot badge

- _includes/sections/email-providers.html
https://deploy-preview-1762--privacytools-io.netlify.com/providers/email/#posteo
Apparently this audit verifies it  https://posteo.de/bfdi_pruefbericht.pdf (german only). Would be good if we could get someone to check that.
Closes: https://github.com/privacytoolsIO/privacytools.io/issues/1761
> Update Posteo payment anonymization

- pages/software/real-time-communication.html
Well written as most EFF articles are.
https://deploy-preview-1768--privacytools-io.netlify.com/software/real-time-communication/#exploiting-centralized-networks
> A New Path for DOJ to Finally Break Encryption

- pages/providers/email.html
https://deploy-preview-1781--privacytools-io.netlify.com/providers/email/#criteria
> Correct mistake from VPN page

- _includes/sections/email-providers.html
https://deploy-preview-1780--privacytools-io.netlify.com/providers/email/#mailbox
> Mention mailbox.org supports Exchange ActiveSync

- _includes/sections/privacy-resources.html
* https://deploy-preview-1804--privacytools-io.netlify.com/#resources
> privacy-resources: delist The Great Cloudwall

- _includes/sections/voice-video-messenger.html
Resolves: #1803
* Netlify preview for the mainly edited page: https://deploy-preview-1817--privacytools-io.netlify.com/software/real-time-communication/#voip
> VoIP warning: sort + mention Zoom

- _includes/sections/voice-video-messenger.html
https://github.com/jitsi/jitsi-meet/issues/4590#issuecomment-608510905
* https://deploy-preview-1816--privacytools-io.netlify.com/software/real-time-communication/#voip
> VoIP: remove Google Analytics warning of Jitsi Meet

- _includes/sections/vpn.html
Per the [most recent activity](https://github.com/privacytoolsIO/privacytools.io/pull/1528#issuecomment-612105347) on the old PR #1528 I have reconfigured this request to make the required changes.
Given that Mullvad now has published Apps on both main app stores for Android and iOS, I have included links and corrected the incorrect documentation that mobile clients were still in the works.
Resolves: #1528 which was erroneously closed. (By me, oops).
[Netlify Preview here](https://eager-colden-4cbe67.netlify.com/providers/vpn/)
N/A
> Updated Mullvad VPN details with Play Store and App Store Links

- _includes/sections/email-providers.html
- _includes/sections/vpn.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1827
https://deploy-preview-1829--privacytools-io.netlify.com/providers/vpn/
https://deploy-preview-1829--privacytools-io.netlify.com/providers/email/
> Fixed pricing for ProtonVPN

- .github/stale.yml
I first suggested it in https://github.com/privacytoolsIO/privacytools.io/issues/977#issuecomment-502433728 and talked about it in Wire where @blacklight447-ptio supports the idea.
I checked the install page and made a request I think will come to @BurungHantu1605 and @JonahAragon and in case you approve it, this file should be created with rules on how it works.
> Add .github/stale.yml for stale bot in case we add it

- _includes/sections/social-networks.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1848
* Netlify preview for the mainly edited page:  https://deploy-preview-1850--privacytools-io.netlify.app/providers/social-networks/#social
> Software Removal | Minds.com

- _includes/cardv2.html
- _includes/sections/instant-messenger.html
- _includes/sections/teamchat.html
- _includes/sections/voice-video-messenger.html
This PR adds privacy policy links to the RTC cards.
* Netlify preview for the mainly edited page:  https://deploy-preview-1860--privacytools-io.netlify.app/software/real-time-communication/
> Add privacy policy links for RTC

- _includes/sections/cloud-storage.html
Resolves: #1870 
* Netlify preview for the mainly edited page: https://deploy-preview-1876--privacytools-io.netlify.app/providers/cloud-storage/
> Add KBFS to Cloud Storage Providers

- _includes/sections/dns.html
https://github.com/privacytoolsIO/privacytools.io/issues/1869#issuecomment-622996340
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1869
* Netlify preview for the mainly edited page:  https://deploy-preview-1873--privacytools-io.netlify.app/providers/dns/#dns
> Remove SecureDNS (service shut down)

- _includes/sections/browser-fingerprint.html
Closes: https://github.com/privacytoolsIO/privacytools.io/issues/1880
https://deploy-preview-1883--privacytools-io.netlify.app/browsers/#fingerprint
> Don't mention specific addons under fingerprinting

- _includes/sections/browser-addons.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1879
https://deploy-preview-1884--privacytools-io.netlify.app/browsers/#addons
> Mention 1st party script blocking (uMatrix)

- _includes/sections/instant-messenger.html
https://matrix.org/blog/2020/05/06/cross-signing-and-end-to-end-encryption-by-default-is-here
* https://deploy-preview-1893--privacytools-io.netlify.app/software/real-time-communication/#federated
> Cross-signing and E2EE on by default in Riot

- _includes/sections/teamchat.html
- _includes/sections/voice-video-messenger.html
https://deploy-preview-1912--privacytools-io.netlify.app/software/real-time-communication/#voip
https://deploy-preview-1912--privacytools-io.netlify.app/software/real-time-communication/#teamchat
> Update warning riot, team and change jitsi link

- _includes/sections/voice-video-messenger.html
https://deploy-preview-1923--privacytools-io.netlify.app/software/real-time-communication/#voip
> Fixed missing oldstyle badge and indenting

- _includes/sections/mobile-operating-systems.html
> Only recommend LineageOS official builds

- _includes/sections/vpn.html
- pages/providers/vpn.html
Resolves: https://github.com/privacytools/privacytools.io/pull/1902#issuecomment-648155638
> Mullvad now available in F-Droid

- pages/software/real-time-communication.html
https://deploy-preview-1965--privacytools-io.netlify.app/software/real-time-communication/#exploiting-centralized-networks
> Add mention of LAED 2020 bill

- _includes/head.html
- _includes/sections/privacy-resources.html
Resolves: #https://github.com/privacytools/privacytools.io/issues/1983 
> Remove Reset the Net from Privacy Resources

- _includes/sections/operating-systems.html
Resolves: asked in the _PrivacyTools Lounge at Matrix_ by @dngray based on my suggestion
- while I hope this is OK as I am not suggesting a new software/service/similar, just expanding the existing recommendations.
- it has been some time though, please tell me if I need to reread it :)
- should be if it's recommended in the first place
* Netlify preview for the mainly edited page: https://deploy-preview-1988--privacytools-io.netlify.app/operating-systems/#os
* Code repository of the project (if applicable): not applicable, already listed
> operating-systems: mention other Fedora Flavours and Ubuntu Spins

- _includes/sections/hosting-provider.html
Resolves: #1919 and #1259
* Netlify preview for the mainly edited page: https://deploy-preview-1992--privacytools-io.netlify.app/providers/hosting/
> Remove Datacell, Orange web hosting providers

- _includes/sections/hosting-provider.html
Resolves: #1920
* Netlify preview for the mainly edited page: https://deploy-preview-1993--privacytools-io.netlify.app/providers/hosting/
> Add warning that Njalla blocks port 25 traffic

- _includes/nav.html
- _includes/sections/operating-systems.html
https://deploy-preview-1995--privacytools-io.netlify.app/operating-systems/#os
> Change PC Operating Systems to Introductory Operating Systems

- pages/providers/vpn.html
Resolves: #2023 
Add a link under "Related VPN information" to the [PrivacyTools Blog Post on VPN Review Sites](https://blog.privacytools.io/the-trouble-with-vpn-and-privacy-reviews/)
* Netlify preview for the mainly edited page: https://deploy-preview-2027--privacytools-io.netlify.app/providers/vpn/
> Add PrivacyTools Blog Post about VPN Review sites

- pages/services/chat.html
Resolves: #2036
While both are federated, they are seperate and calling it the “Matrix fediverse” only adds confusion.
* Netlify preview for the mainly edited page: https://deploy-preview-2045--privacytools-io.netlify.app/services/chat/
> Don’t refer to Matrix as part of the “Fediverse”

- _includes/sections/tor-operating-systems.html
Resolves: #2034 
* Netlify preview for the mainly edited page: https://deploy-preview-2042--privacytools-io.netlify.app/operating-systems/#tor_os
> Added .onion adress for Whonix

- _includes/sections/browser-addons.html
Resolves: https://github.com/privacytools/privacytools.io/issues/2057
* https://deploy-preview-2058--privacytools-io.netlify.app/browsers/#addons
> Mention discontinuation uMatrix, mention uBlock advanced mode

- _includes/sections/key-disclosure-law.html
Resolves: https://github.com/privacytools/privacytools.io/issues/1167 https://github.com/privacytools/privacytools.io/issues/2039
* Netlify preview for the mainly edited page: https://deploy-preview-2062--privacytools-io.netlify.app/providers/#kdl
> No key disclosure in Canada

- _includes/sections/file-sharing.html
Resolves: https://github.com/privacytools/privacytools.io/issues/2055
* Netlify preview for the mainly edited page: https://deploy-preview-2061--privacytools-io.netlify.app/software/file-sharing/
> Firefox send is discontinued

- _includes/sections/browser-tweaks.html
Resolves: #2071  
* Netlify preview for the mainly edited page: https://deploy-preview-2077--privacytools-io.netlify.app/browsers/#about_config
> Update the "about:config" tweaks' instructions

- _includes/sections/cloud-storage.html
- _includes/sections/selfhosted-cloud.html
Resolves: #2054
---
Previews:
* https://5f7e2a50eb1610000860de3b--privacytools-io.netlify.app/providers/cloud-storage/#cloud
* https://5f7e2a50eb1610000860de3b--privacytools-io.netlify.app/software/cloud/#mycloud
> Remove NextCloud's experimental E2EE warning.

- pages/providers/vpn.html
I think this is worthwhile, because VPN companies love to make these sorts of things hard to find, with their expensive mass advertising campaigns to control SEO.
https://deploy-preview-2010--privacytools-io.netlify.app/providers/vpn/#info
> Section introducing VPN breaches

- _includes/sections/file-encryption.html
Resolves: #2064 
* Netlify preview for the mainly edited page: https://deploy-preview-2100--privacytools-io.netlify.app/software/encryption-tools/
* Code repository of the project (if applicable): https://github.com/samuel-lucas6/Kryptor
> Add Kryptor as worth mentioning.

- _includes/sections/email-clients.html
Resolves: #2098 
* Netlify preview for the mainly edited page: https://deploy-preview-2101--privacytools-io.netlify.app/software/email
> Change K-9 Mail's link to the official site.

- _includes/sections/file-encryption.html
https://deploy-preview-2108--privacytools-io.netlify.app/software/encryption-tools/
> Fix labels, to be consistent

- _includes/sections/file-encryption.html
> Remove Keka

- _includes/sections/notebooks.html
EteSync is already listed under contacts/calendars, but there's now also notes support.
Resolves: I went on Matrix and was suggested to just create a PR.
I also checked the boxes below based on that. Let me know if you'd like me to open an issue too.
* Netlify preview for the mainly edited page: https://deploy-preview-2115--privacytools-io.netlify.app/software/notebooks/
* Code repository of the project (if applicable): https://github.com/etesync/etesync-notes/
> Notebooks: added EteSync Notes to worth mentioning.

- assets/css/style.scss
Resolves: https://github.com/privacytools/privacytools.io/pull/2139#issuecomment-751338425 @dngray 
* Netlify preview for the mainly edited page: https://deploy-preview-2167--privacytools-io.netlify.app/
> Fix for tooltips on badge

- pages/providers/vpn.html
> Misspell on the URL Link.

- _includes/sections/browser-addons.html
Closes: https://github.com/privacytools/privacytools.io/issues/2156
> Update Temp container bug

- _includes/sections/browser-recommendation.html
In the Onion Browser's description is written that it is endorsed by the Tor Project, but the Onion Browser's website has no easy to find link to the Tor Project's website to prove it. For readers convenience I have added link to [torproject.org](https://support.torproject.org/glossary/onion-browser/) where they can read about the Onion Browser from the Tor Project's perspective.
I know, this is not Wikipedia and we do not have to source everything, however, in the Firefox for iOS, there is already a link to Disconnect's website, just so readers can find out more about their Tracking protection lists. Being able to quickly verify that the Onion Browser is really officially endorsed by the Tor Project is arguably much more important, therefore the link should be included.
Other, more …
> Onion Browser: link proving Tor Project endorsement

- _includes/sections/dns.html
Resolves #2158 
* Netlify preview for the mainly edited page:  https://deploy-preview-2181--privacytools-io.netlify.app/providers/dns/
> Uncensored DNS now supports DoH

- pages/about/about.html
> Update Matrix Room Links

- _includes/sections/privacy-resources.html
Looks like it was taken over, all I see is just a bunch of ads on this website
> remove: www.erfahrungen.com

- _includes/sections/hosting-provider.html
- _includes/sections/warrant-canary.html
- pages/providers/vpn.html
Resolves: #2233, #2234
Fixes the following issues:
* https://www.privacytools.io/providers/#wc links to https://www.ipredator.se/static/downloads/canary.txt, which is a deadline after the merge (I don't think another warrant canary exists).
* https://www.privacytools.io/providers/hosting/ mentions IPreadator VPN as a separate product and doesn't include Ethereum as an accepted payment.
* https://www.privacytools.io/providers/vpn/#info links to "https://proxy.sh/panel/knowledgebase.php?action=displayarticle&id=5".
* https://www.privacytools.io/providers/#wc links to https://proxy.sh/panel/knowledgebase.php?action=displayarticle&id=5
* Netlify preview for the mainly edited page: https://app.netlify.com/sites/privacytools-io/deploys/604dced90fe4430008c4bb00 (build failed because of unrelated …
> Remove dead links, update info about mentioned companies

- _includes/sections/file-encryption.html
Resolves: #2223 
I also corrected the spelling of macOS and changed the formatting to match the other Worth Mentioning programs.
> Update Kryptor website URL

- _includes/sections/email-providers.html
Resolves: #2349 
- [ x] I understand that by not opening an issue about a software/service/similar addition/removal, this pull request will be closed without merging.
- [ x] I have read and understand [the contributing guidelines](https://github.com/privacytools/privacytools.io/blob/master/.github/CONTRIBUTING.md).
- [ x] The project is [Free Libre](https://en.wikipedia.org/wiki/Free_software) and/or [Open Source](https://en.wikipedia.org/wiki/Open-source_software) Software
> Update ProtonMail's onion section

- _includes/sections/productivity-tools.html
Announcement: https://discuss.write.as/t/tor-onion-service-moved/3188
Resolves: #2387
> Update write.as to Onion v3 address

- _includes/sections/vpn.html
> Correcting Mullvad's onion link
