privacytools/privacytools.io

index.html
corrected headline text “an US” to “a US”
====
Explanation:
when using the articles “a” and “an,” usage choice is governed by
pronunciation not spelling.
If the word following the article begins ***with the sound of*** a
vowel, it should be preceded by “an.”
This is a common mistake, especially in print and text.
In this case, “US” is pronounced “You-Ess,” not “Ooo-Ess.”  The
“Y-sound” is not a vowel-sound, which means it is preceded by “a.”
Hope this helps!
=> Grammar Correction ("an" corrected to "a")

index.html
I don't know of any way to pull this info remotely via javascript or otherwise. But it was a bit surprising to see a list of my previouslly closed tabs even while using private browsing. As seen here.
=> add a tab_undo suggestion to firefox tweaks

index.html
ProtonMail Storage is now 500 MB for new users during the Beta, with the possibility to request more if needed. (It is still 1 GB for users who registered before the change.)
More space will be available in the future as a premium option.
https://support.protonmail.ch/knowledge-base/increase-storage-space/
=> Update ProtonMail Storage

index.html
Tutanota does not accept Bitcoin as payment.
=> Removes Bitcoin support from Tutanota email

index.html
Not sure what this link was doing in the first place, but as it’s not in English (which I understand is the target audience), I think we should remove it.
Also I guess remove a tonne of white space but see line 648 for link removal.
=> Remove foreign link

index.html
Facebook is no longer an option for ChatSecure, because they discontinued their XMPP service in April 2015. I have changed the ChatSecure description to reflect this. [Source](https://developers.facebook.com/docs/chat/).
Side note: It says that one should 'post suggestions' in the subreddit, which I do use, however I take that to mean suggestions for adding or removing software/advice, not minor edits like this. I apologize if minor edits should also be discussed in the sub.
=> Minor edit to 'ChatSecure' description

index.html
Deep web != dark web
And the capitalisation was just weird.
=> Change Deep Web to Dark web

index.html
Replicant:
- Typo "the Android"
CopperheadOS:
- Said it was based on linux, not Android. Ultimately correct, but not relevant.
Wording was a bit verbose, so I took the liberty of rewriting them based on the taglines from each project's website.
=> Update Replicant and Copperhead taglines

index.html
re #80
re: https://www.privacytools.io/#dns
A couple issues here. First, they are an Australian company (Five Eyes)! Second, if you've tried to hit up their homepage since June, you were presented with an expired SSL certificate (https://cloudns.com.au/). Rookie.
How did they become the recommendation? Can we get that recommendation removed? There are plenty of other DNS and DNSCrypt providers out there.
=> remove CloudNS #80

index.html
I think a link to other instances is advisable. That's one of the ideas behind searx and most users looking for searx will probably not see that there's more than one instance. Searx.me isn't neccessarily the best instance for everyone either (it doesn't proxy images by default for example). On the other hand linking to only [github.io](https://asciimoo.github.io/searx/) or [github.com](https://github.com/asciimoo/searx/wiki/Searx-instances) will keep the user from immediatly being able to try searx out and might scare them off. I therefore added a second button linking to the list of instances.
=> Link to searx instances

index.html
It may look nice on devices that display the emoji correctly, <s>but neither in Google Chrome nor Firefox it displays.</s> **Edit:** it depends on OS and font, but is still useless
=> Remove not-displaying emoji

index.html
Qubes should be first. Debian is just a generic distribution, whereas Qubes is about security. Also, [[1]](https://twitter.com/Snowden/status/781493632293605376) [[2]](https://www.qubes-os.org/experts/).
=> Change OS section order

index.html
Service is dying. List of issues copied from [RIP openmailbox forum topic](https://forum.openmailbox.org/viewtopic.php?id=1747)
- SSL certificate for forum expired on Wednesday, December 28, 2016 (hopefully, for webmail it will expire on Thursday, November 16, 2017)
- new registrations still not available (!);
- writting to support@openmailbox.org won't help you to create new account;
- Support was online almost two months ago;
- Outlook Mail doesn't receive my emails;
- XMPP stopped working;
- new version still not ready;
- source code still not published;
- permanent problems with receiving some emails.
- Can't use third party programs like K9-Mail and Thunderbird because of connection timout problems all the time.
- Still all mails are saved in one encrypted volume which the owner has …
=> Remove Openmailbox from email providers

index.html
My comment the other day had a typo, i2paddresshelper was pasted twice somehow.
Thank you for having an i2p site :+1:
=> Fixing I2P jump link

index.html
Hi there,
I was scrolling through and I noticed that the entry for Wire (the encrypted messenger) only listed macOS and Windows for desktop OSes. However, per their [download](https://wire.com/en/download/) page, they have source code and binaries available for Linux. I've been using the Linux app (on Arch) for several months now and it works as intended.
TL;DR: Wire does in fact support Linux.
http://htmlpreview.github.io/?https://github.com/mpcsh/privacytools.io/blob/master/index.html
=> Update Wire entries to reflect Linux support

index.html
CodePlex is shutting down and the VeraCrypt project is moving to veracrypt.fr.
http://htmlpreview.github.io/?https://github.com/b-harper/privacytools.io/blob/update-VeraCrypt-url/index.html
=> update VeraCrypt url

index.html
**Email section: StartMail now accepts Bitcoin. Changed to "Accepted"**
Information to support change: https://support.startmail.com/index.php?/Knowledgebase/Article/View/65/0/bitcoin
This closes privacytoolsIO/privacytools.io#226.
**Search Engine section, worth mentioning:**
Currently, Ixquick.eu is a "worth mentioning" with the following description: 
_ixquick.eu - Returns the top ten results from multiple search engines. Based in the USA and the Netherlands._ 
Updated to the following in the pull request:
ixquick.eu - Returns the top results from multiple search engines. Based in the Netherlands.
**Information to support the change:**
Ixquick.eu is based in the Netherlands only. Not the US. (Ixquick
originated in the US, but was acquired by Surfboard Holding B.V, a
privately held Dutch …
=> StartMail and Ixquick.eu update

index.html
Added links to a Motherboard article to the Related Information sections under Encrypted Instant Messengers and  Encrypted Video & Voice. Adding a disclaimer was also proposed by [a user on Reddit](https://www.reddit.com/r/privacytoolsIO/comments/6auj04/secure_messaging_app_wire_stores_everyone_youve/dhhldfw/?context=3
): "I'd just put a disclaimer ln the site. It really depends on your threat model, but I do think that Wire should find a way to encrypt that data."
I also made some minor aesthetic improvements, like indenting the line about ChatSecure and removing an unnecessary link from Wire's description.
http://htmlpreview.github.io/?https://github.com/NinebitX/privacytools.io/blob/patch-1/index.html
=> Mention that Wire stores metadata

index.html
To be on par with the other websites' addresses, update the name on the button from "Website: getmonero" to "Website: getmonero.org"
http://htmlpreview.github.io/?https://github.com/hugoncosta/privacytools.io/blob/master/index.html
=> Update Monero's website to include .org

index.html
I changed the link to the eff official link, giving the user the ability to choose download the correct version for his browser directly. See #244 
http://htmlpreview.github.io/?https://github.com/hugoncosta/privacytools.io/blob/patch-2/index.html
=> (Re)add Privacy Badger

index.html
I'm exploring all viable options to the conflict.
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/remove-crypto/index.html
=> remove cryptocurrencies

index.html
Adding a Content Security Policy, which you can read about [here](https://scotthelme.co.uk/content-security-policy-an-introduction/), and for implementing it on [GitHub pages](https://qszhuan.github.io/technology/2015/08/12/add_csp_to_github_blog).
```
<meta http-equiv='Content-Security-Policy' content="Content-Security-Policy: default-src 'none'; script-src https://privacytoolsio.github.io"; style-src 'unsafe-inline'>
```
Referrer policy (see [here](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Referrer_Policy)):
```
<meta http-equiv="Referrer-Policy" content="no-referrer">
```
http://htmlpreview.github.io/?https://github.com/C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N/privacytools.io/blob/patch-2/index.html
=> Adding a Content Security Policy and Referrer Policy to index.html

donate.html
Adding a Content Security Policy, which you can read about [here](https://scotthelme.co.uk/content-security-policy-an-introduction/), and for implementing it on [GitHub pages](https://qszhuan.github.io/technology/2015/08/12/add_csp_to_github_blog).
```
<meta http-equiv='Content-Security-Policy' content="Content-Security-Policy: default-src 'none'; script-src https://privacytoolsio.github.io"; style-src 'unsafe-inline'>
```
Referrer policy (see [here](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Referrer_Policy)):
```
<meta http-equiv="Referrer-Policy" content="no-referrer">
```
http://htmlpreview.github.io/?https://github.com/C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N/privacytools.io/blob/master/donate.html
=> Adding CSP and RP to donate.html

password.html
Adding a Content Security Policy, which you can read about [here](https://scotthelme.co.uk/content-security-policy-an-introduction/), and for implementing it on [GitHub pages](https://qszhuan.github.io/technology/2015/08/12/add_csp_to_github_blog).
```
<meta http-equiv='Content-Security-Policy' content="Content-Security-Policy: default-src 'none'; script-src https://privacytoolsio.github.io"; style-src 'unsafe-inline'>
```
Referrer policy (see [here](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Referrer_Policy)):
```
<meta http-equiv="Referrer-Policy" content="no-referrer">
```
http://htmlpreview.github.io/?https://github.com/C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N/privacytools.io/blob/patch-4/password.html
=> Adding a CSP and RP to password.html

webrtc.html
Adding a Content Security Policy, which you can read about [here](https://scotthelme.co.uk/content-security-policy-an-introduction/), and for implementing it on [GitHub pages](https://qszhuan.github.io/technology/2015/08/12/add_csp_to_github_blog).
```
<meta http-equiv='Content-Security-Policy' content="Content-Security-Policy: default-src 'none'; script-src https://privacytoolsio.github.io"; style-src 'unsafe-inline'>
```
Referrer policy (see [here](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Referrer_Policy)):
```
<meta http-equiv="Referrer-Policy" content="no-referrer">
```
http://htmlpreview.github.io/?https://github.com/C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N/privacytools.io/blob/patch-5/webrtc.html
=> Adding a CSP and RP to webrtc.html

index.html
CryptoHeaven doesn't use HTTPS, CounterMail requires Java to even register.
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/Shifterovich-email-patch/index.html
=> Remove bad email providers

index.html
Adding `privacy.resistFingerprinting` and `privacy.firstparty.isolate` documentation for about:config tweaks for Firefox. Partially addresses issue: https://github.com/privacytoolsIO/privacytools.io/issues/272
http://htmlpreview.github.io/?https://github.com/C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N/privacytools.io/blob/patch-6/index.html
(don't be alarmed by the lack of styling, it's a result of the CSP policy.)
=> Adding `privacy.resistFingerprinting` and `privacy.firstparty.isolate` documentation for about:config tweaks for FF (Issue: 272)

index.html
They're currently offline.
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/Shifterovich-remove-darknets/index.html
=> Remove darknet mirrors

index.html
This makes it easier to apply the settings to Firefox, since you shouldn't have
to type in the full setting each time. I have applied these to probably a dozen
Firefox instances, and each time I have wished that the setting names were
sorted and grouped together.
I haven't removed any of the settings nor changed any wording.
I left the privacy settings at the top of the list, since they are the most
relevant.
http://htmlpreview.github.io/?https://github.com/sbennett1990/privacytools.io/blob/master/index.html
=> Group and sort Firefox about:config tweaks

index.html
Firefox 56 will introduce a new feature called "Speculative Connect" which attempts to preload URLs that are autocompleted in the awesome bar. Firefox says it will only do the server DNS lookup and TCP and TLS handshake but not start sending or receiving HTTP data. This could indeed be a performance boost, but it could also be a privacy concern.
Note that this should not be merged until Firefox 56 is released, scheduled for 2017-09-26.
Inspiration: https://www.ghacks.net/2017/07/24/disable-preloading-firefox-autocomplete-urls/
More Technical Details: https://bugzilla.mozilla.org/show_bug.cgi?id=1348275
http://htmlpreview.github.io/?https://github.com/sbennett1990/privacytools.io/blob/master/index.html
=> Add a Firefox tweak to disable autocomplete URL preloading

index.html
All those options are terrible ones. 
From our modmail:
> 
> Related Reddit posts:
> 
> https://www.reddit.com/r/linux/comments/3ew6pz/libreboot_exposes_the_purism_librem_as_fraud/
> 
> https://www.reddit.com/r/linux/comments/69k4l9/purism_librem_laptops_any_feedback_from_real/
> I found some links for ORWL. Unlike Purism, I think they're genuinely trying. But their product has significant problems, are not open, and are vulnerable to a variety of attacks as bad as any mainstream lap/desktop out there.
> 
> Joanna Rutkowska (Qubes OS Goddess) wrote in her blog: https://blog.invisiblethings.org/2016/09/03/thoughts-about-orwl.html
> 
> Then ORWL replied, to their credit, agreeing with many of the points (and likewise, changing some things): …
=> Remove the Secure Hardware section

index.html
As discussed on https://github.com/privacytoolsIO/privacytools.io/issues/84#issuecomment-330030630, I moved qwant to "Worth Mentioning" section, StartPage to 2nd position and re-added DuckDuckGo to third spot. 
I tried to maintain the original text as much as possible, but am willing to push changes if requested.
https://htmlpreview.github.io/?https://github.com/aveao/privacytools.io/blob/master/index.html
(the flag works on local, and seeing that [this repo's preview](http://htmlpreview.github.io/?https://github.com/aveao/privacytools.io/blob/master/index.html) has it broken too, I assume it's a problem with htmlpreview)
=> Moved qwant to Worth Mentioning, SP to 2nd and DDG to 3rd as discussed on #84

index.html
Add suggested values for `network.http.referer.XOriginPolicy` and `network.http.referer.XOriginTrimmingPolicy`
http://htmlpreview.github.io/?https://github.com/groovecoder/privacytools.io/blob/about-config-referer/index.html
=> add Firefox about_config values for Referer

index.html
Small alert in the Mobile OS area with concern to the use of apps made by Google.
http://htmlpreview.github.io/?https://github.com/hugoncosta/privacytools.io/blob/patch-1/index.html
=> Add a warning about GApps

index.html
#347 
http://htmlpreview.github.io/?https://github.com/shifterovich2/privacytools.io/blob/tutorial-buttons/index.html
=> Add links to GPG and PGP tutorials

index.html
Added and unified asterisk usage.
> The suspect and some other persons who have the right or that cannot otherwise by duty be called as witnesses are exempt from this [password/key disclosure] requirement.
=> Key disclosure exemptions

index.html
The MicroG project aims to provide a replacement for the proprietary Google Apps and Services found in the Android operating system (such as Google Play Services). This project is useful because it allows functionality in applications that depend on GAPPS. I added MicroG to the Worth Mentioning section of MobileOS's and to the warning about GAPPS. 
http://htmlpreview.github.io/?https://github.com/sim-s-singh/privacytools.io/blob/microg/index.html
=> Add MicroG Project to MobileOS Section

index.html
Although it's not possible to disable WebRTC in Chrome, an API exists to change its routing settings.
The API can be used to prevent leaks using extensions.
*index.html* currently mentions that only a single extension exists, and that it can be easily circumvented. 
This is no longer true. 
The old extension (which has been removed by its developer) attempted to block WebRTC by injecting JavaScript into web pages (a content script). This solution is flawed because it's not possible to inject code into a sandboxed iframe.
Current extensions use an API provided by Chrome, and cannot be circumvented.
https://htmlpreview.github.io/?https://github.com/aghorler/privacytools.io/blob/master/index.html
=> List open source means to prevent WebRTC leaks in Chrome.

index.html
This was requested on Reddit: https://www.reddit.com/r/privacytoolsIO/comments/7fz9fj/update_needed_signal_app_now_have_desktop/
Signal Desktop does not support voice and video calling yet. I think we can wait until it does before we add mentions of the desktop platforms to that section.
http://htmlpreview.github.io/?https://github.com/NinebitX/privacytools.io/blob/patch-2/index.html
=> Mention desktop platforms in the Signal entry

index.html
add ipfs to the self contained networks section
http://htmlpreview.github.io/?https://github.com/emanresusername/privacytools.io/blob/master/index.html
=> add ipfs to the self contained networks section

index.html
As mentioned in #365, we talked about replacing the link to the deprecated Firefox extension "Random Agent Spoofer" to the new "User Agent Switcher" that works with FF57+.
http://htmlpreview.github.io/?https://github.com/stefnats/privacytools.io/blob/master/index.html
=> Switched deprecated User-Agent Switcher Firefox extension

index.html
Someone sniped the domain https://dnscrypt.org/
Might redirect to malware in the future
#384 
http://htmlpreview.github.io/?https://github.com/privacytoolsIO/privacytools.io/blob/dnscrypt/index.html
=> temporary dnscrypt stop

index.html
- Added "browser.sessionstore.privacy_level = 2" to Firefox: Privacy Related "about:config" Tweaks. See #310 
- Added "network.IDN_show_punycode = true" to Firefox: Privacy Related "about:config" Tweaks. Not rendering IDNs as their punycode equivalent leaves you open to phishing attacks that can be very difficult to notice. [source](https://krebsonsecurity.com/2018/03/look-alike-domains-and-visual-confusion/#more-42636)
http://htmlpreview.github.io/?https://github.com/neverducky/privacytools.io/blob/aboutconfig-additions/index.html#about_config
=> about:config add sessionstore and punycode rendering tweaks

index.html
This PR removes F-Droid in OS line under i2p. Check commits for better understanding.
F-Droid is not an OS, it will be confusing for new users. Instead can we add another line saying, "Available on F-Droid"?
http://htmlpreview.github.io/?https://github.com/avizini/privacytools.io/blob/master/index.html
=> Replace Android with BSD / Solaris under i2p

index.html
Add back DNSCrypt, as per discussion in #384. List of platforms has also been updated.
We may also want to change the logo, as the current one does not match the one on the website.
http://htmlpreview.github.io/?https://github.com/NPN/privacytools.io/blob/reinstate-dnscrypt/index.html
=> Reinstate DNSCrypt

index.html
As per Wikipedia, LibreWRT was merged to LibreCMC in 2015:
https://en.wikipedia.org/wiki/LibreCMC
http://htmlpreview.github.io/?https://github.com/c0rdis/privacytools.io/blob/c0rdis-patch-1/index.html
=> Replace LibreWRT with LibreCMC

index.html
[Their website says](https://disroot.org/en/services/email):
> Mailbox size limit: 2GB
http://htmlpreview.github.io/?https://github.com/wi24rd/privacytools.io/blob/patch-1/index.html
=> fix disroot.org mail storage

index.html
I noticed the sorting for "Own Domain" in the email section was not working for StartMail. The data-value attribute was not inline with text and the actual features listed on StartMail's website.
http://htmlpreview.github.io/?https://github.com/nearwood/privacytools.io/blob/master/index.html
=> Fix StartMail's "Own Domain" data-value

index.html
Firefox automatically downloads and installs the Widevine Content Decryption Module provided by Google Inc. (the Widevine CDM for short).
There are two (apparently undocumented) **about:config** rules that deal with this plugin: `media.eme.enabled` and `media.gmp-widevinecdm.enabled`.
* `media.eme.enabled = false`
This is equivalent to unchecking the _Play DRM-controlled content_ checkbox in the Options, and it will disable playback of DRM-controlled HTML5 content, which, if enabled, automatically downloads the Widevine CDM. This setting automatically uninstalls the Widevine CDM plugin. Setting `media.eme.enabled` to `true` again automatically reinstalls it.
* `media.gmp-widevinecdm.enabled = false`
This is equivalent to selecting _Never Activate_ from the dropdown menu of the Widevine …
=> Add about:config rules for preventing Firefox from downloading and enabling the Widevine CDM by Google

index.html
Add Pi-hole (https://pi-hole.net/) to the suggestions for DNS.  Works quite well as a network DNS server, blocking ad and tracker domains (and anything else you feel like blocking).
http://htmlpreview.github.io/?https://github.com/sjlehn/privacytools.io/blob/master/index.html
=> Add Pi-hole as worth mentioning under DNS

index.html
Remove all the openmailbox URL
Openmailbox has been removed since https://github.com/privacytoolsIO/privacytools.io/pull/163
https://htmlpreview.github.io/?https://github.com/Kcchouette/privacytools.io/blob/patch-1/index.html
=> Remove all the openmailbox URL

index.html
The syntax for the referrer policy was wrong. Therefore, the referrer policy was not actually enabled.
See also: https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fprivacytools.io%2F
https://htmlpreview.github.io/?https://github.com/rsnitsch/privacytools.io/blob/master/index.html
=> Fix referrer policy

README.md
- The Chinese translation link now points to the website instead of the repository
- Italian links now point to the right website and repository
=> Fix Community Translations links

index.html
Limit the amount of identifiable information sent when requesting the Mozilla harmful extensions blocklist.
From Reddit user /u/LocalFigurez at https://old.reddit.com/r/privacytoolsIO/comments/9uqeew/firefox_tip_sanitize_firefox_blocklist_url_so_it/
Firefox includes feature that connects in regular time intervals (every 24 hour) to the Mozilla's servers to download blocklist of harmful extensions, vulnerable plugins and crash-prone graphic drivers. This request includes following information:
APP_ID
APP_VERSION
PRODUCT
VERSION
BUILD_ID
BUILD_TARGET
OS_VERSION
LOCALE
CHANNEL
PLATFORM_VERSION
DISTRIBUTION
DISTRIBUTION_VERSION
PING_COUNT
TOTAL_PING_COUNT
DAYS_SINCE_LAST_PING
By changing `extensions.blocklist.url` from 
https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%APP_ID%/% …
=> Changing the extensions.blocklist.url flag

index.html
findx.com and ixquick.eu have both shut down.
Issue: #none
=> Remove findx.com and ixquick.eu from Search Engines

index.html
The legacy Chrome version of Signal Desktop was officially deprecated on October 31, 2017, and has now officially expired:
https://github.com/signalapp/Signal-Desktop/commit/6c8cff56bba165ad4addfde8db0c923283b11ebb#diff-2650fb3e14b7f42d68a8766269c54434R130
=> Remove "Web" from the Signal entries

_layouts/default.html, _sass/_vars.scss, assets/css/style.scss, index.html
Issue: #584 
Replace Google+ share button with Mastodon.
=> Replace Google+ share button with Mastodon

index.html
There are no active key disclose laws in Sweden (only proposed).
Source: https://www.wikipedia.org/wiki/Key_disclosure_law#Sweden
=> There are NO active key disclosure laws in Sweden.

index.html
This will remove a redirection hop.
Also, `https://[www.]kekaosx.com` gives ERR_SSL_PROTOCOL_ERROR.
=> Fixing link to keka file archiver

index.html
This fixes the "Five Eyes" list formatting.  PRs #625 #643 and #646 didn't implement this properly, thus can now be closed.
Fixes #625
Fixes #643
Fixes #646
=> Fix Five Eyes lists

index.html
Resolves: #654  
Seems like Northern Cyprus likely uses Turkey's laws which are definitely not good for a VPN provider.
=> Remove EarthVPN

_config.yml, robots.txt
I disagree with the decision to remove robots.txt in #668. I think it may at least remove 404 errors from logs and sitemap.xml can only help with SEO or won't be harmful.
However I am not sure if privacytools.io has more than one page and I was unable to get Jekyll working locally on this PC.
=> Enable sitemap.xml generation & reintroduce robots.txt

index.html
As talked about in issue #719 Bitwarden has Google Analytics baked in and enabled by default. This commit removes Bitwarden from the recommended programs and relegates it to last place in the "worth mentioning" list, with the warning about disabling Google Analytics if it is used.
Resolves: #719
=> Removed Bitwarden

_includes/sections/search-engines.html
We always capitalize proper nouns and adjectives derived from them.
=> Fix european to European

_includes/sections/email-alternatives.html
We should move i2p-bote to worth mentioning, due to the website not having a working build available and due to the fact that its development is effectively stalled.
It is also somewhat hard to use due to it only working with I2P.
We could replace it with ZeroMail: https://github.com/HelloZeroNet/ZeroMail although ZeroMail doesn't get much development either anymore.
=> Moved i2p-bote to worth mentioning due to lack of development

_includes/sections/privacy-resources.html
Replace broken link for Block Cloudflare MITM Attack Addon
Resolves: #442
=> Replace broken link

_includes/nav.html
Participate link didn't link to homepage on non-index.html pages.
=> Fix participate link

assets/css/style.scss
Add body { word-wrap: break-word; } to break up long strings on mobile devices. Just looks better.
Resolves: #610
After:
Before:
=> Break long words on smaller devices

_includes/scripts.html
Moving from `piwik.privacytools.io` the new stats server at `stats.privacytools.io`. Don't merge this request until we move to the new DNS infrastructure from CloudFlare and @BurungHantu1605 makes their superuser account on the new stats site.
=> Update to stats.privacytools.io

_includes/sections/footer.html, privacy-policy.html
Adds a privacy policy to the site and footer for this site, our Matomo tracking, and our services. This privacy policy is based heavily off https://www.opennic.org/privacy/ -- if someone could check and make sure everything fits with this project, that would be great.
Do not merge until:
---
Related: #475
=> Create Privacy Policy

_includes/sections/file-encryption.html
Remove AES Crypt from the "worth mentioning" section of file encryption because
- there appears to be [known issues](https://web.archive.org/web/20121029141517/https://www.aescrypt.com/wishlist.html) with the current file format they utilize. This issue allows anybody to truncate encrypted files without being detected.
- the issues [won't be fixed anytime soon](https://github.com/paulej/AESCrypt/issues/23).
- the code [doesn't appear to be under any kind of open source license](https://github.com/paulej/AESCrypt).
Resolves: #805
Related info: [Reddit thread](https://old.reddit.com/r/privacytoolsIO/comments/b7riov/aes_crypt_security_audit_1_serious_issue_found/)
=> Remove AES Crypt

.well-known/matrix/client, _config.yml
This is just for some Matrix configuration right now, but we'll use it for whatever needs site-verification/configuration in the future.
=> Add .well-known folder for Matrix

donate.html
*Apparently* normal addresses [are totally *out*](https://www.bitcoinabc.org/2018-01-14-CashAddr/) for Bitcoin Cash, and CashAddrs are *in*. Converted our wallet with https://cashaddr.bitcoincash.org/
=> Update to BCH CashAddr

_includes/sections/social-networks.html
Related info:
https://support.google.com/plus/answer/9195133?hl=en
https://www.iol.co.za/business-report/technology/google-launches-replacement-for-google-called-google-currents-20966583
=> Remove Google+ mention, because it is gone

_includes/sections/browser-tweaks.html
Reverts privacytoolsIO/privacytools.io#865
https://www.bleepingcomputer.com/news/software/mozilla-firefox-to-enable-hyperlink-ping-tracking-by-default/
=> Revert "browser-tweaks: remove browser.send_pings"

_includes/sections/resources.html
The classic button wasn't within the first screenful of text, so I missed it while reopening and closing #882.
Resolves: #882
=> WIP: resources: move the classic site on top for more visibility

_includes/sections/instant-messenger.html
Other messengers have the Experimental tag so Ricochet should as well since it is considered as such by the author and is documented right in the readme and on the website.
=> Add Experimental note to Ricochet

_includes/sections/dns.html
NoTrack Has Moved To GitLab - changed URL link
=> Updated URL link for NoTrack

_includes/sections/vpn.html
**Description**: Add WireGuard support to VPN provider table/comparison.
**Why?**: Personally, I couldn't run a VPN without WireGuard, OpenVPN was too taxing on my already slow speeds. This helps show users that OpenVPN isn't the only way to utilize a VPN.
**But isn't WireGuard beta?** Yes, but this PR isn't about recommending WireGuard. Instead it is about making it easier for users to choose for themselves. 
**Has this been discussed before?** Yes, #633 .
=> Add Wireguard to VPN Providers

_includes/sections/instant-messenger.html
Resolves: #948 
Ricochet is considered experimental, not easy to use and is no longer actively maintained.  See discussions #948  #840 
The latest commit on https://github.com/ricochet-im/ricochet was almost 2 years ago.
Also see:
https://github.com/ricochet-im/ricochet/issues/578
One of the lead developers is now focusing on another project:
https://openprivacy.ca/
That does not mean Ricochet is flawed, but it was always considered experimental and it is for advanced users only who need to setup and keep Tor up to date.
Wire was originally an IM recommendation, but then replaced with Riot.  Riot is not easy to make entirely private, but it is still a good option for advanced users.  So with one easy recommendation (Signal) which is primarily for mobile device use, that leaves currently …
=> Swap Ricochet and Wire

_includes/sections/instant-messenger.html
Resolves: #948 
Combine all the XMPP clients into one list.  Also change recommendations:
-Replace ChatSecure with Monal
-Add Gajim (Linux)
Also remove link to Wikipedia list of OTR clients and replace with link to omemo.top website.
=> Cleanup and combine XMPP client list.  

.github/CONTRIBUTING.md
**The Issue**: As privacytools.io has grown more criteria for products has been added,
For instance VPNs must be "outside the US, use encryption, accept Bitcoin, support OpenVPN and have a no logging policy."
The software criteria in the contributing guidelines has not updated with this.
**What do you propose?**
> ### Main
> - Easy to use. Could your mother use that tool or service? Usability is most important.
> - Cross-platform / Accessible.
> - Privacy respecting.
> - Open Source / free software is preferred but not required.
> - Must list source code in [source_code.md](https://github.com/privacytoolsIO/privacytools.io/blob/master/source_code.md) (if applicable)
> - Prioritize Products without Vendor Lock-in (decentralized/self-hostable) or data interoperability.
> 
> There can be …
=> Discussion | Update Software Criteria

.well-known/security.txt, SECURITY.md
As recommended in #988:
> Since privacytools.io has somewhat recently become a service provider, I suggest we have an official bug reporting policy.
This sounds good to me. I added some basic instructions to a security policy file, do you think this is enough or well-constructed? Let me know if anything should be added @beardog108.
---
Closes #988
=> Add Security Policy

_includes/sections/instant-messenger.html
Closes: #1007
Closes: #1004
Closes: #1023 (supersedes)
See also: #840
=> instant-messenger: add privacy concerns warning to Riot

_includes/sections/email-providers.html, _includes/sections/vpn.html
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1058
- Updated the "Website" column for both Email and VPN providers to not be sortable (doesn't make sense?) and to say "Website" for consistency vs "URL" like it was for the Email table.
- Added Mullvad's Tor link. Not sure if I'm missing others?
=> Add Tor URL to VPN Provider website column

_includes/sections/email-clients.html
GTK+ was renamed to just GTK, some time ago.
https://mail.gnome.org/archives/gtk-devel-list/2019-February/msg00000.html
=> GTK+ was renamed to GTK

_includes/cardv2.html, _includes/sections/email-clients.html
Thunderbird is no longer developed by Mozilla.
https://blog.mozilla.org/thunderbird/2017/05/thunderbirds-future-home/
github.com/thundernest does not contain source code of Thunderbird client
> comm-central is the main Thunderbird repository.
> Thundernest contains the code for Thunderbird.net (this site),
as well as the Thunderbird web server setup scripts.
from https://www.thunderbird.net/en-US/get-involved/
In _includes/cardv2.html add `source`, because git is not the only
version control available (there is Mercurial, Subversion, CVS)
=> Update information about Thunderbird and avoid repetition

_includes/sections/instant-messenger.html, source_code.md
We previously added a warning on privacy concerns in #1024 after
Prism-break had delisted Riot and *Notes on privacy and data collection
of Matrix.org* was released revealing concerns even with self-hosted
homeservers.
Today Libre Monde has released another part on privacy investigation on
Matrix.org [1] revealing that they aren't GDPR compliant nor privacy
friendly and behave shadily such as by announcing removal of data as a
result of GDPR request. [2]
[1]:https://github.com/libremonde-org/paper-research-privacy-matrix.org/blob/master/part2/README.md
[2]:https://github.com/libremonde-org/paper-research-privacy-matrix.org/blob/master/part2/README.md#the-request
Resolves: #840
=> instant-messengers: delist Riot

_includes/sections/vpn.html
This PR adds onion service URLs for cryptostorm and ExpressVPN.
ExpressVPN's link is taken from [here](https://www.expressvpn.com/blog/expressvpn-launches-tor-onion/) and cryptostorm's from their [home page](https://cryptostorm.is/).
=> Add Onion service URLs for cryptostorm and ExpressVPN

pages/providers/vpn.html
This PR adds a warning to the VPN page detailing the drawbacks and risks of using a VPN, and suggesting the use of Tor to ensure anonymity in most cases.
https://deploy-preview-1090--privacytools-io.netlify.com/providers/vpn/
Closes #914
=> Add warnings to VPN section, encourage Tor use

README.md
If it will ever be changed, it will save 10 seconds confusion and will work for offline markdown rendering tools
=> Get logo from local path in README.md

_includes/sections/self-contained-networks.html
Change Tor Browser to Tor, as TB is not a network.
Update Android informations, we don't live in 2008!
https://2019.www.torproject.org/docs/android.html.en
has instructions for 1.X, 2.X and most of the links are broken
=> Update information about Tor in Self-Contained Networks

_includes/sections/android-addons.html, assets/css/style.scss
This PR hopefully increases the UX on the [Android Addons page](https://www.privacytools.io/operating-systems/#aaddons) by adding 50 pixels of top padding to the icons conditionally (using a [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)) on the "large" Bootstrap layout until the layout collapses for smaller screens.
=> Conditionally add top padding to Android addons icons

_config.yml, _includes/nav.html, pages/software/im.html, pages/software/real-time-communication.html, pages/software/teamchat.html, pages/software/video-voice.html
Resolves: #1078
Closes: #746
Preview: https://deploy-preview-1136--privacytools-io.netlify.com/software/real-time-communication/
=> Merge im, teamchat and video-voice into real-time-communication

_includes/cardv2.html, _includes/nav.html, _includes/sections/browser-addons.html, _includes/sections/browser-recommendation.html
Reordered the sub-navigations for "browser" and "os" to make more logical sense, not sure why they were alphabetized with the rest.
Renamed sections to be browser-agnostic.
Added support for adding links to platform icons in cardv2.html:
Icons left blank (as they all currently are) will remain functionally the same, for example:
```
firefox=""
chrome=""
safari=""
opera=""
edge=""
android=""
```
However, adding a link to one:
```
chrome="https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en"
```
...will add a hyperlink to that icon (the same way the Git icons are currently linked), allowing us to link to download pages for various platforms. All platform icons now support this functionality, although it will be most useful for linking browser …
=> Small Improvements

_includes/sections/file-encryption.html, source_code.md
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1056
Code Repository (if applicable): https://github.com/sh-dv/hat.sh
=> Add Hat.sh to File Encryption page

_includes/sections/dns.html
This PR adds a tooltip to the providers who support DoT over port 443 in addition to the expected port 853. This is an important indication because like DoH, DoT/443 makes eavesdropping more difficult for third parties and provides the benefit of not easily being blocked by firewalls compared to 853.
- ~~[ ] This project has an [associated discussion](https://github.com/privacytoolsIO/privacytools.io/issues).~~ (via Wire chat)
=> Indicate which DNS providers support DoT over port 443

_includes/sections/dns.html
This PR adds a new section for giving users easy to follow steps to validate their encrypted DNS connection is working for them. Definitely open to any feedback to make this clearer and more readable.
@Mikaela did note in the issue:
> Should we note here [in Firefox's `about:networking#dns` step] that it's normal that some first queries such as captive portal checking may be going plaintext? Is it OK that our instructions allow downgrading to insecure DNS if DoH is down? I guess as optimally the user has global DNS encryption and eDNS is just going to benefit as DoH?
I address this by saying `If the TRR column says "true" for some fields, you are using DoH.` Maybe this could be changed to something more clearer?
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1152 
- …
=> Add section to validate DNS connection

assets/css/style.scss
This PR updates tables' rows to be vertically align to `middle` (center of the row) which seems to improve overall UX.
- https://deploy-preview-1235--privacytools-io.netlify.com/providers/dns/
- https://deploy-preview-1235--privacytools-io.netlify.com/providers/email/
=> Center table row values

_includes/head.html, _includes/nav.html, assets/css/dark.scss, assets/css/style.scss, assets/js/main.js
Fixes #1151
* Install Firefox Developer Edition (up-to-date Firefox and Safari (https://github.com/privacytoolsIO/privacytools.io/pull/1204#issuecomment-524510658) should also be fine):
https://www.mozilla.org/en-US/firefox/developer/
* Firefox gets data from operating system to decide if user prefers dark themes, so set it to dark in system settings or execute it like this (Adwaita is included with GTK, so you should have it installed):
White theme:
```
$ GTK_THEME=Adwaita ./firefox-developer/firefox
```
Dark theme:
```
$ GTK_THEME=Adwaita-dark ./firefox-developer/firefox
```
Or you can go to `about:config` and add a property named `ui.systemUsesDarkTheme`, `integer` and set it to `1`.
__Note:__ `privacy.resistFingerprinting` must be false.
After you do that, there is an option to open …
=> Add dark theme

_includes/sections/password-managers.html
Currently points to KeePassXC's GitHub repository -- my mistake.
* Netlify preview for the mainly edited page: https://deploy-preview-1238--privacytools-io.netlify.com/software/passwords/#pw
=> Fix LessPass GitHub link

_includes/scripts.html, _layouts/minimal.html, assets/js/applytheme.js, assets/js/main.js
It should at least fix going `dark -> light -> dark` when `prefers-color-scheme` was set to `dark` and user changed to light theme and then back to dark using a switch.
It can probably fix other flickering as JavaScript used for loading theme set by using a switch is now loaded at the top of `<body>`, I guess.
=> Reduce flickering with dark/light theme

_includes/sections/teamchat.html
Adds link to [Keybase's onion service](https://keybase.io/docs/command_line/tor): http://keybase5wmilwokqirssclfnsqrjdsi7jdir5wy7y7iu3tanwmtp6oid.onion/
https://deploy-preview-1255--privacytools-io.netlify.com/software/real-time-communication/#teamchat
=> Add Onion service URL for Keybase

_includes/sections/email-providers.html
Like the DNS table, this keeps flags with country names on the same line for readability.
* Netlify preview for the mainly edited page: https://deploy-preview-1260--privacytools-io.netlify.com/providers/email/#email
=> Don't wrap text for jurisdiction column in Email Providers table

_includes/sections/dns.html, source_code.md
Resolves: #1258 
While OpenNIC and Namecoin allow private domain registration, I am let to understand that they cannot get SSL certificates, that are globally recognised as valid, due to their nature as an alternative to ICANN managed DNS.
If I am correct, this results to them either not having https/TLS at all or teaching users to blindly accept any SSL certificates, either announcing in plaintext to any network listener (or Tor exit node) what they are doing or leaving them vulnarable to MITM attackers. Thus I don't consider them as private.
See also:
* https://github.com/privacytoolsIO/privacytools.io/issues/1258#issuecomment-528486198
* https://github.com/opennic/opennic-web/issues/68 …
=> Delist OpenNIC & NameCoin

.gitignore
It's generated by Jekyll on my machine with `bundle exec jekyll serve --livereload --incremental`
=> gitignore .jekyll-metadata

_includes/sections/privacy-resources.html
* openwireless.org, see also: https://github.com/privacytoolsIO/privacytools.io/issues/1184
* Keybase: we list it on other sections and the description is a bit unhelpful.
>  <li><a href="https://keybase.io/"><strong>Keybase.io</strong></a> - Get a public key, safely, starting just with someone's social media username.</li>
While there is a "search Keybase on top", I think this description should either be removed or changed a lot as Keybase's homepage doesn't advertise this capability and instead advertises itself as kind of a team chat and file sync.
* https://deploy-preview-1279--privacytools-io.netlify.com/#resources
=> privacy-resources: delist Keybase, list Open Wireless Movement

_includes/nav.html
I don't see any other solution to this (no, changing paddings is not the solution).
=> Remove "Contact" from navbar

_includes/sections/dns.html
Updated the Nixnet protocol field by adding "DoH" as it also offers DNS over HTTPS.
* Netlify preview for the mainly edited page:  https://deploy-preview-1321--privacytools-io.netlify.com/providers/dns/
=> Add DoH to NixNet

_includes/footer.html
It is being removed because https://kopimi.com blocks all Tor traffic.
=> Remove kopimi from the footer

_includes/sections/browser-addons.html
Resolves: #1301 where moving Privacy Badger on the bottom was given as a requirement for keeping it.
* Netlify preview for the mainly edited page: https://deploy-preview-1306--privacytools-io.netlify.com/browsers/#addons
=> browser-addons: put Privacy Badger on bottom

_includes/sections/teamchat.html
I am just wondering if it's a better link than an web.archive.org link to a closed feature request for a single privacy feature where they say to not have any plans for it, while there are more things wrong with them.
=> teamchat: link to ToSDR instead of web.archive.org

password.html
It was redirecting to `index.html#pw`, but we don't have that id in new
layout, it only exists in ` /classic/`, but such redirect to `/classic/#pw`
doesn't make any sense and was broken for some time, so clearly nobody
cares.
=> Remove password.html, it's not needed anymore

_includes/sections/browser-addons.html
NOTE: I don't have any personal macOS device.
Since Catalina, addons have to be written in Swift and use new API. Legacy
addons, don't work anymore and new API is much more limited in terms of
content blocking. https://github.com/el1t/uBlock-Safari/issues/158
TOS;DR is written in JavaScript and last commit was on 2013, so yeah.
https://deploy-preview-1347--privacytools-io.netlify.com/browsers/#addons
=> Remove addon links which don't work with up-to-date Safari

_includes/sections/dns.html
See https://en.wikipedia.org/wiki/User:Giraffedata/comprised_of for more information.
Resolves: No issue: Arguably incorrect English. "comprised of" is viewed as incorrect by some, because comprise and compose have distinct meanings. See [this page](https://en.wikipedia.org/wiki/User:Giraffedata/comprised_of) for a good rundown of the issue.
The other check boxes are not applicable for this commit I believe.
=> Change "comprised of" to "composed of"

build.sh
Systems like OpenBSD, FreeBSD, NetBSD or macOS (might be removed soon
https://support.apple.com/en-us/HT208050) don't have bash installed.
This script should run perfectly fine with POSIX `sh`.
=> Replace bash with sh in build.sh for compatibility

_includes/sections/operating-systems.html
TL;DR: This changes `mds=full,nosmt` to its superset `mitigations=auto,nosmt` which includes all CPU mitigation support of Linux kernel. I understand that `nosmt=force` means that the root user cannot restore SMT after boot by running a sysctl command to adjust kernel configuration runtime. While I am unsure whether it's really needed in our scope, I would say better safe than sorry.
To quote the kernel doc https://www.kernel.org/doc/html/latest/admin-guide/kernel-parameters.html
mitigations=
[X86,PPC,S390,ARM64] Control optional mitigations for
CPU vulnerabilities.  This is a set of curated,
arch-independent options, each of which is an
aggregation of existing arch-specific options.
off
Disable all optional CPU mitigations.  This
improves system performance, but it may also
expose users …
=> operating-systems: include the supersets instead of just mds

_includes/sections/dns.html
Ref: ookangzheng/blahdns#66
https://deploy-preview-1396--privacytools-io.netlify.com/providers/dns/#icanndns
=> DNS: BlahDNS has unblocked UTF-8 domains

_includes/footer.html, _includes/nav.html, index.html, pages/sponsors.html
This sponsorship program is designed to allow companies, organizations, and individuals partner with the privacytools.io team to support our vision of a more privacy-respecting internet and the greater online community.
In exchange for financial support, we will provide companies with the exposure and recognition that they are supporting privacy education online. We will do so by displaying their logo and link on various portions of privacytools.io as described on the sponsors page in this PR.
Context: The privacytools.io website receives well in excess of 250,000 pageviews monthly and is ranked highly for privacy-related searches.
- Your name and link along with a small logo or avatar on the sponsors page of this website.
- Your medium-sized logo as a link at the top of our sponsors …
=> privacytools.io sponsorships

_includes/sections/self-contained-networks.html
Resolves: #1286
- Changes self-contained networks to use cardv2
- Adds in links to the git repositories and forum discussions
- Didn't add any links to actual software, but this is up for discussion
Preview: https://deploy-preview-1459--privacytools-io.netlify.com/software/networks/
=> Convert self-contained networks to cardv2

_includes/footer.html
OpenCollective is not the only way to donate. We should just refer users to the donate page (which already emphasizes OpenCollective at the top anyway) if a user prefers to donate via cryptocurrencies.
PR changes:
* Changes link of "Support Us" from `https://opencollective.com/privacytoolsio#section-contribute` to `/donate/`
* Change "ad free" to "ad-free" and adjust grammar of the last bit
* Move href attribute to the front to be more consistent with the others
=> footer: Change link and tooltip of "Support Us!"

_includes/sections/file-encryption.html
Apologies for this very late PR.
Resolves: https://github.com/privacytoolsIO/privacytools.io/pull/1288/files
* Netlify preview for the mainly edited page: https://deploy-preview-1484--privacytools-io.netlify.com/software/encryption-tools/#encrypt
=> Add warning to Cryptomator that its mobile apps are not open-source

_includes/sections/file-encryption.html
Windows only encryption software which has not been updated since version 1.1.846.118 was released on 2014-07-09.
Website certificate has been expired **since on 2019-06-22** which is 4 months, 23 days ago, this is **unacceptable** for encryption software.
An attack could occur whereby someone could be subject to a [MiTM](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) and accept a fraudulent certificate. gpg signatures could be also replaced with this kind of attack so that makes gpg signing the binary pointless. Many people don't check these anyway.
On a side note there appears to be **no** administrative moderation on their forums. Allowing [posts like this one](https://diskcryptor.net/forum/index.php?topic=5424.msg12276#msg12276) in your release thread which declare "UEFI" a …
=> Delist DiskCryptor

_includes/nav.html, assets/css/style.scss
Before hamburger menu was floated to the right with a fixed margin-top,
which means that it probably wasn't perfectly centered and if we would
change logo image size, we would have to edit that margin manually.
=> Layout mobile navbar nicely with Flexbox

pages/about.html
I am against listing Keybase as the PGP host, because they are a centralized service and may terminate accounts at any time. Also I cannot link keys to https://mikaela.info/PGP/0xB2F32B67.txt as it excludes existence of SSH and all the other key types (e.g. minisign?).
Of course now I am giving that power to gitea.blesmrt.net, but at least that instance is not for-profit business.
Later I may move the keys onto IPFS to be more sure that they won't be tampered with.
=> about: don't link to Keybase for my keys

_includes/sections/calendar-contacts-sync.html
The dav bridge install instructions will soon be moved so better to
use the new links now already (for now, they are just a redirect).
As the commit message says it improves the EteSync entry by adding a link to the new iOS app, improving the description and changing the soon to be deprecated DAV installation instructions links.
* Netlify preview for the mainly edited page: https://deploy-preview-1490--privacytools-io.netlify.com/software/calendar-contacts/
The project is already on privacy-tools, though anyhow, here's the source code: https://github.com/etesync/
=> Improve EteSync: add iOS link, improve description and change links

_includes/sections/operating-systems.html
This fixes a grammar mistake in the _CPU vulnerability mitigations_ section of the Operating Systems page ("a enough recent Linux kernel" to "a recent enough Linux kernel"). A reference to the kernel commit that added the `vulnerabilities/` directory could also be added. Here is a link to the commit: [http://lkml.iu.edu/hypermail/linux/kernel/1801.1/00145.html](http://lkml.iu.edu/hypermail/linux/kernel/1801.1/00145.html)
* Netlify preview for the mainly edited page: [https://deploy-preview-1506--privacytools-io.netlify.com/operating-systems/#cpuvulns](https://deploy-preview-1506--privacytools-io.netlify.com/operating-systems/#cpuvulns)
=> Fix grammar in CPU vulnerability section

_plugins/translated-page-generator.rb
This fixes the permalink generation. 
Permalinks from before looked like
``
http://localhost:4000es//sponsors/
``
Now, they should look like
``
http://localhost:4000/es/sponsors/
``
=> i18n: Fix permalink generation

_includes/sections/email-providers.html
> BTW: Encryption is built in to the web client these days. You can update your
> schema.
According to someone from Kolab Now, they now support PGP encryption.
I could found more information about that on
https://kb.kolabnow.com/documentation/encryption
https://deploy-preview-1521--privacytools-io.netlify.com/providers/email/
=> Kolab Now Webclient now supports PGP encryption

_plugins/weblate-source-file.rb, weblate-source-file.yml
This is to make  don't end up using the same string for two
strings using the same words but different length and punctuation.
For example, there are two strings of different length on the site that started with this exact substring:
> You are being watched. Private and state-sponsored organizations are monitoring and recording your online activities.
As a result, the shorter string on the site ended up being superseded by the longer string. I had to bump the max base key length up from 100 to 150. Encoding the length in the key makes sure we don't run into this issue in the future for even longer strings.
=> i18n: Encode length and punctuation in key IDs

_plugins/weblate-source-file.rb
See https://github.com/privacytoolsIO/privacytools.io/pull/1509#issuecomment-558552605. This PR should get rid of `\n` in the parsed YAML (https://yaml.org/YAML_for_ruby.html#three_trailing_newlines_in_literals)
Not including a source file change in this one as I think it's better to let you handle source file refreshes (also, I have other PRs that add new keys anyway)
=> i18n: strip all newlines for Weblate

_includes/sections/instant-messenger.html
The sentence about metadata flows better if the second fragment is used as an example of metadata
=> Use e.g., instead of eg for instant messengers

pages/providers/email.html, pages/software/email.html
This adds a warning to the email lists that (even with GPG) email is insecure for many reasons and should not be entrusted with sensitive communications. It recommends using a IM platform like Signal for that kind of thing.
Related: #1542 
* Netlify preview for the mainly edited page: https://deploy-preview-1543--privacytools-io.netlify.com/providers/email/
=> Add security warning to email lists

assets/js/main.js
JavaScript was checking if element clicked is exactly `.nav-summary`,
which isn't a problem when just clicking text inside it, but if we try
to click another element inside like `<span>`, it won't work, since now
this span is clicked, not `.nav-summary`.
Closes #1549
=> Fix collapsing navbar dropdown when clicking another element

_includes/sections/android-addons.html, _includes/sections/browser-addons.html, _includes/sections/browser-recommendation.html, _includes/sections/calendar-contacts-sync.html, _includes/sections/cloud-storage.html, _includes/sections/dns.html, _includes/sections/email-clients.html, _includes/sections/email-providers.html, _includes/sections/file-encryption.html, _includes/sections/file-sharing.html, _includes/sections/file-sync.html, _includes/sections/instant-messenger.html, _includes/sections/live-operating-systems.html, _includes/sections/mobile-operating-systems.html, _includes/sections/notebooks.html, _includes/sections/operating-systems.html, _includes/sections/password-managers.html, _includes/sections/search-engines.html, _includes/sections/self-contained-networks.html, _includes/sections/selfhosted-cloud.html, _includes/sections/social-networks.html, pages/os.html, pages/providers/dns.html, pages/providers/email.html, pages/providers/social-networks.html, pages/software/networks.html, pages/software/passwords.html, pages/software/real-time-communication.html
This PR corrects some sentences I didn't like, and rearranges the content of the website a bit.
Recommendations and worth mentioning products should generally go in the `_includes/sections` folder, while supplemental information (such as VPN criteria, news on E2EE, and other "further reading") should go directly on the page in `/pages`. This makes that guideline more consistently applied across the site.
=> Rearrange some sections and correct grammatical errors

_includes/breadcrumbs.html, pages/providers/dns.html, pages/providers/vpn.html, pages/software/cal-card.html
- Adds breadcrumb attribute to YAML front-matter for pages where we would like to define a particular breadcrumb name rather than the auto-generated one.
- Example: https://deploy-preview-1555--privacytools-io.netlify.com/providers/dns/
- Capitalizes every word of the breadcrumb name rather than only the first.
- Example: https://deploy-preview-1555--privacytools-io.netlify.com/providers/social-news-aggregator/
Resolves: #1551
=> Make breadcrumbs nicer looking

pages/providers/vpn.html
Uses affiliate links, we don't want to be driving traffic there. Recommends VPNs that do not fit our criteria.
=> Remove wirecutter, affiliate driven site, talks about VPNs we don't recommend anyway

_includes/sections/browser-recommendation.html
This PR changes the wording to be closer to Bromite's own description and mentions ungoogled-chromium instead of GrapheneOS.
Resolves: #1588
=> Change wording to be closer to Bromite's own description

_includes/sections/browser-tweaks.html
Button had been changed to "Accept the Risk and Continue" so I've updated that. More information at #1602
Resolves: https://github.com/privacytoolsIO/privacytools.io/issues/1532
=> Change a warning of Firefox about:config entering

_includes/sections/notebooks.html
I am looking for some sort of a todo list and happened to notice that we are linking to Notable's GitHub while they have a homepage.
* Netlify preview for the mainly edited page: https://deploy-preview-1633--privacytools-io.netlify.com/software/notebooks/#notebook
=> notebooks: link to Notable's homepage instead of GitHub

.github/ISSUE_TEMPLATE/5_Website_Issues.md
This should just be applied on a case-by-case basis rather than as a label that external contributors cannot remove when creating an issue.
=> No "high priority" tag for Website Issue template

_includes/sections/key-disclosure-law.html
Resolves: #1696
* Change link from https://en.wikipedia.org/wiki/Key_disclosure_law#Belgium to https://tweakers.net/nieuws/163116/belgische-rechter-verdachte-mag-verplicht-worden-code-smartphone-af-te-staan.html (the judgment supercedes the old law).
* Remove the star.
* Netlify preview for the mainly edited page: https://deploy-preview-1700--privacytools-io.netlify.com/providers/#kdl
=> Remove star and update link for key disclosure laws for Belgium

_includes/sections/vpn.html, pages/providers/vpn.html
https://deploy-preview-1705--privacytools-io.netlify.com/providers/vpn/
I've also updated the criteria to now require open source clients. These really are just wrappers around a VPN client which is already open source so there's no reason providers in the future that are added can't make sure they are open source.
=> Source code for IVPN now available

.github/PULL_REQUEST_TEMPLATE.md
The link was broken since it was pointing to https://github.com/privacytoolsIO/privacytools.io/blob/master/CODE_OF_CONDUCT.md instead of https://github.com/privacytoolsIO/.github/blob/master/CODE_OF_CONDUCT.md but on that version it explicitly says "_Please refer to the full text on our wiki when referencing this document._" so I changed the link to point to the CoC on the wiki instead.
=> Fixed PR template broken link to CoC

_includes/sections/participate.html
The link to Mastodon was pointing to the instance itself and not @privacytools. Users looking for our instance can find it on https://www.privacytools.io/services/. Removed the link for Mastodon that was in the paragraph above the button as it was a duplicate.
Resolves: #1371 
* Netlify preview for the mainly edited page: https://deploy-preview-1776--privacytools-io.netlify.com/index.html#participate
=> Add link to CoC and correct Mastodon link on Participate section

_includes/sections/browser-addons.html, _includes/sections/browser-webrtc.html
Closes: #1483 
Closes: #298 
Closes: #1522
* Netlify preview for the mainly edited page: https://deploy-preview-1773--privacytools-io.netlify.com/browsers/#webrtc
=> Solve issues related to WebRTC

_includes/sections/browser-tweaks.html
Resolves: #1594 and Part 1&2a of #1430 
Removed the sentence about redundancy because it is not truly redundant (i.e. privileged pages), and explaining to uBO users how to adjust their settings to handle privileged pages would be too complicated; the filter list overlap is not that important.
Moved the thing about DoH and stuff to the bottom for aesthetic reasons.
I wasn't sure how to handle the bundle of prefetch tweaks, whether to: 
1. Put them all one after the other with an explanation at the bottom
2. Write a description for each (even though the nuances are barely important IMO) and take up a bunch of space
3. Make a sublist about prefetch and just put them all together
After a bunch of thinking I went with 3. since it seemed like the most elegant and logical option but if anyone …
=> Add new browser tweaks and remove deprecated info

_includes/sections/instant-messenger.html
Resolves: #1727 
Changes:
* Add label warning that Jami is partially centralized
* Extend description to mention all communications are end-to-end encrypted, including through TURN servers if used.
* Netlify preview for the mainly edited page: https://deploy-preview-1752--privacytools-io.netlify.com/software/real-time-communication/#peer-to-peer
=> add partial centralization warning for Jami

pages/providers/vpn.html
removes a link on the vpn page which spread miss information about Tor.
* Netlify preview for the mainly edited page: https://deploy-preview-1798--privacytools-io.netlify.com/providers/vpn/
=> remove bad vpn link

_includes/sections/file-sync.html
Resolves: #1309 
It seems that the project maintainer has moved onto working on FigmaSharp. There have only been 16 commits to Sparkleshare since the start of 2019: 3 in Jan19, 3 in May19, 4 in Jan20 and 6 in Feb20. Most of these commits are trivial changes (12 commits with under 10 changes each) to README or bumping version numbers. The "activity" at the start of this year was merging a pull request for Libravatar support. The Windows version is severely outdated and he doesn't care about maintaining it, [saying that the outdated version will be the last one](https://github.com/hbons/SparkleShare/issues/1909#issuecomment-526943216).
I think it is safe to say that this project is not maintained anymore. The question is whether that really matters. If the project was "feature-complete" as …
=> Remove Sparkleshare from File Sync

_includes/cardv2.html, assets/css/style.scss
This MR attempts to update v2 cards to be more mobile friendly; specifically letting the card buttons flex. Also will allow more buttons to fit in the future (for example, the Qwant card below adds a "Privacy Policy" button).
Netlify: https://deploy-preview-1849--privacytools-io.netlify.app/
=> Update cardv2 for mobile layouts

_includes/cardv2.html, _includes/sections/social-news-aggregator.html
This MR adds privacy policy links to the Social News Aggregator cards for easier reference.
Netlify preview for the mainly edited page: https://deploy-preview-1857--privacytools-io.netlify.app/providers/social-news-aggregator/
=> Add privacy policy links to Social News Aggregator cards

_includes/cardv2.html, _includes/sections/search-engines.html
This MR cleans up the search engine page a bit by updating some descriptions for clarity and consistency along with adding a new Cardv2 link for a privacy policy button to add to the DuckDuckGo and Qwant cards.
The Google Search WebExtension for Firefox has also been removed since usage of Google conflicts with our warning banner to avoid using Google/Bing/Yahoo.
* Netlify preview for the mainly edited page: https://deploy-preview-1844--privacytools-io.netlify.app/providers/search-engines/#search
Dependent PR:
=> Add privacy policy links to Search Engine cards

_includes/sections/mobile-operating-systems.html, _includes/sections/operating-systems.html, _includes/sections/router-firmware.html
Adds links to available privacy policies in the OS pages.
* Netlify preview for the mainly edited page:  https://deploy-preview-1862--privacytools-io.netlify.app/operating-systems/#os
=> Add privacy policy links for OS pages

_includes/sections/search-engines.html
Startpage listing cleanup:
- Use correct branding (**Startpage.com** vs StartPage)
- Alphabetizes listings (besides Searx, a metasearch software platform rather than a provider)
- Changes "obsessive" description to a more neutral tone: `Startpage BV is a Netherlands-based company that has been dedicated to privacy-respecting search since 2006.`
=> Update Startpage.com Listing

_includes/sections/browser-fingerprint.html
closes #1899 
Adds target="_blank" to the panopticlick.eff.org links.
=> fixed missing link code

_includes/sections/browser-addons.html
This pull request fixes a typo in our description of the clearurl addon.
* Netlify preview for the mainly edited page: https://deploy-preview-1953--privacytools-io.netlify.app/browsers/#addons
=> fix typo in clear url description

_includes/sections/instant-messenger.html
Closes: https://github.com/privacytools/privacytools.io/issues/1978
https://deploy-preview-1979--privacytools-io.netlify.app/software/real-time-communication/#centralized
=> Remove erroneous NextCloud link from Signal badge

_includes/sections/browser-recommendation.html
The original link for the Onion Browser on the iOS Browser Recommendations (located at: https://www.privacytools.io/browsers/#browser-ios) (original link: https://onionbrowser.com/#security-advisories) defaulted to the homepage with no information about iOS's limitations. Replaced it with the about page which has information on the limitations.
Resolves: https://github.com/privacytools/privacytools.io/issues/1999
=> Updated Onion Browser iOS limitations link

_includes/sections/instant-messenger.html, _includes/sections/teamchat.html, pages/services/chat.html
https://deploy-preview-2012--privacytools-io.netlify.app/services/chat/
=> Some more fixes for the chat page

_includes/sections/browser-recommendation.html
- Had generic source logo before even though it link to a GitHub page
Resolves: #2024  
Previously, the links to the source code for both [Firefox for Android](https://www.privacytools.io/browsers/#browser-android) and [Firefox for iOS](https://www.privacytools.io/browsers/#browser-ios) had a generic "source" icon even though it linked to a GitHub page. 
* Netlify preview for the mainly edited page: https://5f45ae359ced2e0008aeae76--privacytools-io.netlify.app/browsers/
=> Change Icon for Firefox Mobile Source Code

pages/providers/vpn.html
- This link concerns the video "This Video Is Sponsored By ███ VPN" by Tom Scott, with the Video ID "WVDQEoe6ZWY".
- The [Indivious](https://github.com/iv-org/invidious) instance hosted under the domain "invidio.us" shut down on September 1st, 2020
(I am not particularly sure if 'similar addition' falls under this category. All I did was replace a broken link, which doesn't amount to adding a new service on the list.)
Not applicable.
https://github.com/iv-org/invidious
=> Replaced invidio.us link with an alternative Individuous instance

_includes/sections/dns.html
Resolves: 
1. Blahdns do not filter IDN already.
2. Added Singapore server.
3. Blahdns do have uncensored DNS only for DoH, e.x: https://doh1.blahdns.com/uncensor 
* Netlify preview for the mainly edited page: https://deploy-preview-2025--privacytools-io.netlify.app/providers/dns/
=> Remove datacenter and announce Singapore server

_includes/sections/router-firmware.html
Resolves: Re-add librecmc, as it's not effected by the vulnerability described in https://github.com/privacytools/privacytools.io/pull/1969#issuecomment-653838449 it was removed in error as a part of [#1969](https://github.com/privacytools/privacytools.io/pull/1969/files#diff-25892b00fe2b03c7038f28b5eb5c5e2eL26-L34)
* Netlify preview for the mainly edited page: https://deploy-preview-2067--privacytools-io.netlify.app/operating-systems/#firmware
=> Librecmc, not affected by iGPU vulnerability

_includes/sections/dns.html
This PR updates the link for the Anonymized DNSCrypt relays from the [legacy v2 version](https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v2/relays.md) to the [current v3 version](https://github.com/DNSCrypt/dnscrypt-resolvers/blob/master/v3/relays.md), which is now used on the [Anonymized DNSCrypt wiki page](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Anonymized-DNS).
I wasn't sure if I should open an Issue for such a minor fix, as it is not a new software suggestion, but if that is preferred, please let me know.
* Netlify preview for the mainly edited page: https://deploy-preview-2076--privacytools-io.netlify.app/providers/dns/
=> Update Anonymized DNSCrypt relays link to v3

_includes/sections/android-addons.html
Before it was simply “#clients” which is no longer a correct section on the DNS providers page
Resolves: #2073 
* Netlify preview for the mainly edited page: https://deploy-preview-2074--privacytools-io.netlify.app/operating-systems/#aaddons
=> Change Android DNS Client Anchor Link to go to Correct Section

_includes/sections/dns.html
Resolves: #2059
Resolves: #2096
- I am not sure if *AdGuard* profiles cont as it's listed above on the page.
- I don't know if *NextDNS* profile generator is open source.
- *encrypted-dns.party* is open source.
* Netlify preview for the mainly edited page: https://deploy-preview-2099--privacytools-io.netlify.app/providers/dns/#appledns
* Code repository of the project (if applicable): https://gitlab.com/nitrohorse/ios14-encrypted-dns-mobileconfigs
=> DNS: document iOS 14+ & macOS Big Sur encrypted DNS

pages/about/librejs.html
Resolves: None.  This seems like such a minor and straightforward fix, that I thought it will be more helpful to you to just have a pull request directly, for you to sign off on with a single click.
But if this doesn't work for you, I can always go create an issue instead.
=> Fix broken Bootstrap license link in LibreJS page

pages/providers/vpn.html
* https://deploy-preview-2114--privacytools-io.netlify.app/providers/vpn/
So it appears that thatoneprivacysite.net has been sold to another company with just a fairly generic blog. Likely they offered him a lucrative deal for the domain because of the click through rate. These media companies always harass us and ask us to sell our domain to them.
They then just direct it to some fairly generic blog with superficial "tests" and tonnes of affiliate links. The result is low-quality noise that prevents anyone from finding meaningful information. The owners would likely operate many of these websites, which purely exist to generate money for the owners. **The tests are purposely very surface level**, as this requires no work to maintain.
I really think the information provided by …
=> Remove ThatOnePrivacySite

pages/about/about.html
Change the mention of "Riot" to "Element" and update the privacytools.io URL accordingly.
Resolves: #2150
=> Change Riot Name and Link to Element

_includes/sections/vpn.html
Resolves: #2159
As stated in #2159 it seems to be not longer the case that IVPN has a 3 day trial. After a quick wayback machine trip I've found that it had been removed between [October 24th, 2020](https://web.archive.org/web/20201024085618/https://www.ivpn.net/pricing) and [November 26th, 2020](https://web.archive.org/web/20201126002358if_/https://www.ivpn.net/pricing). Whereby at merging #1174 August 17th, 2019 was still true. However now they've removed the trial and [acknowledge](https://www.ivpn.net/knowledgebase/billing/does-ivpn-offer-a-free-trial/) their is no such thing *anymore*. The notice on privacytools.io can be removed as well.
* Netlify preview for the mainly edited page: https://deploy-preview-2178--privacytools-io.netlify.app/
=> Remove trial notice IVPN

_includes/sections/cloud-storage.html, _includes/sections/file-encryption.html
Resolves: #2174
As noted in #2174 currently Cryptomator has an warning for their mobile apps not being open-sourced. Also as stated in #2174 a [blog from Cryptomator](https://cryptomator.org/blog/2020/12/23/android-open-source/) that they've [open-sourced their Android app](https://github.com/cryptomator/android). I've [build](https://bin.privacytools.io/?0c7fce2de934ff90#E0SLKujjWtCHvUjn2VvWHzNmAzVO3En9MjHdW+QfwVo=) the app myself to make sure it is all of their code and not `partially`, after installing it and seeing the compiled source code everything was their with no limitations.
Thereby they are [planning](https://github.com/cryptomator/android/issues/1#issuecomment-752992114) to submit the android app to F-Droid.
After confirming it's fully open-source with no limitations the …
=> Remove warning from Cryptomator

_includes/sections/video-frontends.html
Resolves: #2144
As described in #2144 the current box is misleading, which I agree with. To clarify why I agree with this:
- As a new user(private window) and open a video you can see it will by default request the video from an google server `googlevideo.com` as seen in the [source code](https://github.com/iv-org/invidious/blob/168376b04671c6e362468267a3b07dd332b40702/src/invidious.cr#L211) where they add the CSP headers when the user has not enabled `local`.
- As seen in the [source code](https://github.com/iv-org/invidious/blob/168376b04671c6e362468267a3b07dd332b40702/src/invidious/helpers/helpers.cr#L38) the default preference for `local` which is the preference to see if the user wants proxied video, is false and by default not proxied if not otherwise changed in the preference *if …
=> Add warning to Invidious

_includes/sections/header.html
The URL to pass searches to was https://search.privacytools.io/searx, instead of https://search.privacytools.io. So I changed the URL of the search bar form.
Resolves: #2085  
https://deploy-preview-2086--privacytools-io.netlify.app/
=> Fix search bar not passing searches to Searx

_includes/sections/operating-systems.html
The CI system is a fuzzer for finding upstream and doesn't necessarily reflect the progress made in Arch. The CI are just checking out some files and builds them twice.
The link moves this to our current rebuilder setup which reproduces distributed packages.
=> Arch Linux: Ensure correct link to reproducible builds

_includes/sections/dns.html
Same as #2146.
I asked on [#libreops:matrix.org](https://riot.im/app/#/room/#libreops:matrix.org) if DNSSEC is supported by the LibreDNS service, the answer is:
> [not yet , on our todo list](https://matrix.to/#/!ixcbtfIBdcPeyDEEzR:matrix.org/$161427370750989iDLZN:matrix.org?via=chat.weho.st&via=matrix.org&via=privacytools.io)
Tested with the following commands:
$ kdig @116.202.176.26 +tls-host=dot.libredns.gr +dnssec sigfail.verteiltesysteme.net
;; TLS session (TLS1.3)-(ECDHE-SECP256R1)-(RSA-PSS-RSAE-SHA256)-(AES-256-GCM)
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 8416
;; Flags: qr rd ra; QUERY: 1; ANSWER: 2; AUTHORITY: 0; ADDITIONAL: 1
;; EDNS PSEUDOSECTION:
;; Version: 0; flags: do; UDP size: 512 B; ext-rcode: NOERROR
;; QUESTION SECTION:
;; sigfail.verteiltesysteme.net.		IN	A …
=> LibreDNS doesn't support DNSSEC

_includes/sections/dns.html
Resolves: #2212
https://quad9.net/news/blog/quad9-public-domain-name-service-moves-to-switzerland-for-maximum-internet-privacy-protection/
=> DNS: mark Quad9 as Switzerland based

.github/ISSUE_TEMPLATE/1_Software_Suggestion.md
This is just a small fix for spelling mistakes in the issue template.
=> Fix spelling mistakes in the issue template

_includes/sections/instant-messenger.html
It's a trivial change to match what was done for Signal, as I guess it's important for users to know if there was an independent audit to assess their threat model. I can open an issue if necessary.
=> Add link to audit for Element messenger

_includes/sections/dns.html
Removal of NixNet DNS because they are [shutting down](https://docs.nixnet.services/NixNet_DNS) their DNS service.
Removal of LibreDNS because they do not support DNSSEC.
Resolves:  #2404
Resolves:  #2157
Resolves: #2216 
Resolves: #2411 
=> Remove NixNet DNS and LibreDNS
